---
title: "kNN COVID-19 dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loading libraries}
library(ggplot2)
library(GGally)
if(!require(plyr)){install.packages("plyr")}
library(plyr)
if(!require(dplyr)){install.packages("dplyr")}
library(dplyr)
if(!require(reshape2)){install.packages("reshape2")}
library(reshape2)
if(!require(caret)){install.packages("caret")}
library(caret)
if(!require(corrplot)){install.packages("corrplot")}
library(corrplot)

```

```{r loading data}
covid.data <- read.csv("data/covid-19/covid-19.csv",header=T)
covid.data = covid.data[,2:ncol(covid.data)]
covid.data$result = as.factor(covid.data$result)
head(covid.data)
summary(covid.data)
str(covid.data)
```


```{r violin}
ggplot(covid.data, aes(result, location, fill=result)) +
  geom_violin(aes(color = result), trim = T)+
  scale_y_continuous("Location", breaks= seq(0,150, by=10))+
  geom_boxplot(width=0.1)+
  theme(legend.position="none")

ggplot(covid.data, aes(result, country, fill=result)) +
  geom_violin(aes(color = result), trim = T)+
  scale_y_continuous("Country", breaks= seq(0,50, by=5))+
  geom_boxplot(width=0.1)+
  theme(legend.position="none")

ggplot(covid.data, aes(result, symptom1, fill=result)) +
  geom_violin(aes(color = result), trim = T)+
  scale_y_continuous("Symp1", breaks= seq(0,25, by=2))+
  geom_boxplot(width=0.1)+
  theme(legend.position="none")

ggplot(covid.data, aes(result, age, fill=result)) +
  geom_violin(aes(color = result), trim = T)+
  geom_boxplot(width=0.1)+
  theme(legend.position="none")

```

```{r jitter}
pdf("vio_jitter_covid.pdf", width = 10, height = 5)
exploratory.covid <- melt(covid.data)
exploratory.covid %>%
  ggplot(aes(x = factor(variable), y = value)) +
  geom_violin() +
  geom_jitter(height = 0, width = 0.1, aes(colour = result), alpha = 0.7) +
  theme_minimal()
dev.off()
```

```{r ggpairs}
pdf("all_info_covid.pdf", width=20, height=20)
ggpairs(covid.data, ggplot2::aes(colour = result, alpha = 0.4))
dev.off()

```

```{r splitting into training and test}
covidClass <- covid.data$result
covidData <- covid.data[,1:13]

set.seed(42)
trainIndex <- createDataPartition(y=covidClass, times=1, p=0.7, list=F)
classTrain <- covidClass[trainIndex]
dataTrain <- covidData[trainIndex,]
classTest <- covidClass[-trainIndex]
dataTest <- covidData[-trainIndex,]
summary(dataTrain)
summary(dataTest)
```

```{r}
nzv <- nearZeroVar(dataTrain, saveMetrics=T)
print(nzv)
print(rownames(nzv[nzv$nzv==TRUE,]))
listtoexclude = c(rownames(nzv[nzv$nzv==TRUE ,]))
listtoexclude = c(listtoexclude,rownames(nzv[nzv$zeroVar==TRUE ,]))
```

```{r}
featurePlot(x = dataTrain,
            y = classTrain,
            plot = "box",
            ## Pass in options to bwplot()
            scales = list(y = list(relation="free"),
                          x = list(rot = 90)),
            layout = c(3,3))

#density plot for each variable in training set
featurePlot(x = dataTrain,
            y = classTrain,
            plot = "density",
            ## Pass in options to xyplot() to
            ## make it prettier
            scales = list(x = list(relation="free"),
                          y = list(relation="free")),
            adjust = 1.5,
            pch = "|",
            layout = c(3, 3),
            auto.key = list(columns = 3))

```


```{r}
corMat <- cor(dataTrain)
corrplot(corMat, order="hclust", tl.cex=1)
highCorr <- findCorrelation(corMat, cutoff=0.5)
length(highCorr)
names(dataTrain)[highCorr]
listtoexclude = c(listtoexclude,names(dataTrain)[highCorr])
```

```{r}
tuneParam <- data.frame(k=seq(1,50,2))
set.seed(42)
seeds <- vector(mode = "list", length = 101)
for(i in 1:100) seeds[[i]] <- sample.int(1000, length(tuneParam$k))
seeds[[101]] <- sample.int(1000,1)

train_ctrl <- trainControl(method="repeatedcv",
                           number = 10,
                           repeats = 10,
                           preProcOptions=list(cutoff=0.75),
                           seeds = seeds)

```

```{r}
knnFit <- train(dataTrain, classTrain,
                method="knn",
                preProcess = c("center", "scale", "corr"),
                tuneGrid=tuneParam,
                trControl=train_ctrl)
knnFit
#plotting accuracy against k
plot(knnFit)
plot(knnFit,metric="Kappa")

```


```{r}
test_pred <- predict(knnFit, dataTest)
confusionMatrix(test_pred, classTest)
```

```{r}
dataTrain_restricted = dataTrain[, -which(names(dataTrain) %in% listtoexclude)]

dataTest_restricted = dataTest[, -which(names(dataTest) %in% listtoexclude)]
train_ctrl_restricted <- trainControl(method="repeatedcv",
                           number = 10,
                           repeats = 10,
                           preProcOptions=list(cutoff=0.75),
                           seeds = seeds)

knnFit_restricted <- train(dataTrain_restricted, classTrain,
                method="knn",
                preProcess = c("center", "scale", "corr"),
                tuneGrid=tuneParam,
                trControl=train_ctrl_restricted)
plot(knnFit_restricted)
plot(knnFit_restricted,metric="Kappa")

```
