<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Clustering | An Introduction to Machine Learning</title>
  <meta name="description" content="Course materials for An Introduction to Machine Learning" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Clustering | An Introduction to Machine Learning" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="figures/cover_image.png" />
  <meta property="og:description" content="Course materials for An Introduction to Machine Learning" />
  <meta name="github-repo" content="bioinformatics-training/intro-machine-learning-2019" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Clustering | An Introduction to Machine Learning" />
  
  <meta name="twitter:description" content="Course materials for An Introduction to Machine Learning" />
  <meta name="twitter:image" content="figures/cover_image.png" />

<meta name="author" content="Sudhakaran Prabakaran, Matt Wayland and Chris Penfold" />


<meta name="date" content="2020-10-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dimensionality-reduction.html"/>
<link rel="next" href="nearest-neighbours.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About the course</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#registration"><i class="fa fa-check"></i><b>1.2</b> Registration</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>1.3</b> Prerequisites</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#github"><i class="fa fa-check"></i><b>1.4</b> Github</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i><b>1.5</b> License</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i><b>1.6</b> Contact</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i><b>1.7</b> Colophon</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#what-is-machine-learning"><i class="fa fa-check"></i><b>2.1</b> What is machine learning?</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#aspects-of-ml"><i class="fa fa-check"></i><b>2.2</b> Aspects of ML</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#what-actually-happened-under-the-hood"><i class="fa fa-check"></i><b>2.3</b> What actually happened under the hood</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html"><i class="fa fa-check"></i><b>3</b> Dimensionality reduction</a><ul>
<li class="chapter" data-level="3.1" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#linear-dimensionality-reduction"><i class="fa fa-check"></i><b>3.1</b> Linear Dimensionality Reduction</a><ul>
<li class="chapter" data-level="3.1.1" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#interpreting-the-principle-component-axes"><i class="fa fa-check"></i><b>3.1.1</b> Interpreting the Principle Component Axes</a></li>
<li class="chapter" data-level="3.1.2" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#horseshoe-effect"><i class="fa fa-check"></i><b>3.1.2</b> Horseshoe effect</a></li>
<li class="chapter" data-level="3.1.3" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#pca-analysis-of-mammalian-development"><i class="fa fa-check"></i><b>3.1.3</b> PCA analysis of mammalian development</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#exercise-2.3."><i class="fa fa-check"></i><b>3.2</b> Exercise 2.3.</a></li>
<li class="chapter" data-level="3.3" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#nonlinear-dimensionality-reduction"><i class="fa fa-check"></i><b>3.3</b> Nonlinear Dimensionality Reduction</a><ul>
<li class="chapter" data-level="3.3.1" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#stochasticity"><i class="fa fa-check"></i><b>3.3.1</b> Stochasticity</a></li>
<li class="chapter" data-level="3.3.2" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#analysis-of-mammalian-development"><i class="fa fa-check"></i><b>3.3.2</b> Analysis of mammalian development</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dimensionality-reduction.html"><a href="dimensionality-reduction.html#other-dimensionality-reduction-techniques"><i class="fa fa-check"></i><b>3.4</b> Other dimensionality reduction techniques</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>4</b> Clustering</a><ul>
<li class="chapter" data-level="4.1" data-path="clustering.html"><a href="clustering.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="clustering.html"><a href="clustering.html#distance-metrics"><i class="fa fa-check"></i><b>4.2</b> Distance metrics</a></li>
<li class="chapter" data-level="4.3" data-path="clustering.html"><a href="clustering.html#hierarchic-agglomerative"><i class="fa fa-check"></i><b>4.3</b> Hierarchic agglomerative</a><ul>
<li class="chapter" data-level="4.3.1" data-path="clustering.html"><a href="clustering.html#linkage-algorithms"><i class="fa fa-check"></i><b>4.3.1</b> Linkage algorithms</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="clustering.html"><a href="clustering.html#k-means"><i class="fa fa-check"></i><b>4.4</b> K-means</a><ul>
<li class="chapter" data-level="4.4.1" data-path="clustering.html"><a href="clustering.html#algorithm"><i class="fa fa-check"></i><b>4.4.1</b> Algorithm</a></li>
<li class="chapter" data-level="4.4.2" data-path="clustering.html"><a href="clustering.html#choosing-initial-cluster-centres"><i class="fa fa-check"></i><b>4.4.2</b> Choosing initial cluster centres</a></li>
<li class="chapter" data-level="4.4.3" data-path="clustering.html"><a href="clustering.html#choosingK"><i class="fa fa-check"></i><b>4.4.3</b> Choosing k</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="clustering.html"><a href="clustering.html#dbscan"><i class="fa fa-check"></i><b>4.5</b> DBSCAN</a><ul>
<li class="chapter" data-level="4.5.1" data-path="clustering.html"><a href="clustering.html#algorithm-1"><i class="fa fa-check"></i><b>4.5.1</b> Algorithm</a></li>
<li class="chapter" data-level="4.5.2" data-path="clustering.html"><a href="clustering.html#implementation-in-r"><i class="fa fa-check"></i><b>4.5.2</b> Implementation in R</a></li>
<li class="chapter" data-level="4.5.3" data-path="clustering.html"><a href="clustering.html#choosing-parameters"><i class="fa fa-check"></i><b>4.5.3</b> Choosing parameters</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="clustering.html"><a href="clustering.html#example-clustering-synthetic-data-sets"><i class="fa fa-check"></i><b>4.6</b> Example: clustering synthetic data sets</a><ul>
<li class="chapter" data-level="4.6.1" data-path="clustering.html"><a href="clustering.html#hierarchic-agglomerative-1"><i class="fa fa-check"></i><b>4.6.1</b> Hierarchic agglomerative</a></li>
<li class="chapter" data-level="4.6.2" data-path="clustering.html"><a href="clustering.html#k-means-1"><i class="fa fa-check"></i><b>4.6.2</b> K-means</a></li>
<li class="chapter" data-level="4.6.3" data-path="clustering.html"><a href="clustering.html#dbscan-1"><i class="fa fa-check"></i><b>4.6.3</b> DBSCAN</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="clustering.html"><a href="clustering.html#evaluating-cluster-quality"><i class="fa fa-check"></i><b>4.7</b> Evaluating cluster quality</a><ul>
<li class="chapter" data-level="4.7.1" data-path="clustering.html"><a href="clustering.html#silhouetteMethod"><i class="fa fa-check"></i><b>4.7.1</b> Silhouette method</a></li>
<li class="chapter" data-level="4.7.2" data-path="clustering.html"><a href="clustering.html#example---k-means-clustering-of-blobs-data-set"><i class="fa fa-check"></i><b>4.7.2</b> Example - k-means clustering of blobs data set</a></li>
<li class="chapter" data-level="4.7.3" data-path="clustering.html"><a href="clustering.html#example---dbscan-clustering-of-noisy-moons"><i class="fa fa-check"></i><b>4.7.3</b> Example - DBSCAN clustering of noisy moons</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="clustering.html"><a href="clustering.html#example-gene-expression-profiling-of-human-tissues"><i class="fa fa-check"></i><b>4.8</b> Example: gene expression profiling of human tissues</a><ul>
<li class="chapter" data-level="4.8.1" data-path="clustering.html"><a href="clustering.html#hierarchic-agglomerative-2"><i class="fa fa-check"></i><b>4.8.1</b> Hierarchic agglomerative</a></li>
<li class="chapter" data-level="4.8.2" data-path="clustering.html"><a href="clustering.html#k-means-2"><i class="fa fa-check"></i><b>4.8.2</b> K-means</a></li>
<li class="chapter" data-level="4.8.3" data-path="clustering.html"><a href="clustering.html#dbscan-2"><i class="fa fa-check"></i><b>4.8.3</b> DBSCAN</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="clustering.html"><a href="clustering.html#exercises"><i class="fa fa-check"></i><b>4.9</b> Exercises</a><ul>
<li class="chapter" data-level="4.9.1" data-path="clustering.html"><a href="clustering.html#clusteringEx1"><i class="fa fa-check"></i><b>4.9.1</b> Exercise 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html"><i class="fa fa-check"></i><b>5</b> Nearest neighbours</a><ul>
<li class="chapter" data-level="5.1" data-path="clustering.html"><a href="clustering.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#classification-simulated-data"><i class="fa fa-check"></i><b>5.2</b> Classification: simulated data</a><ul>
<li class="chapter" data-level="5.2.1" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#knn-function"><i class="fa fa-check"></i><b>5.2.1</b> knn function</a></li>
<li class="chapter" data-level="5.2.2" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#plotting-decision-boundaries"><i class="fa fa-check"></i><b>5.2.2</b> Plotting decision boundaries</a></li>
<li class="chapter" data-level="5.2.3" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#bias-variance-tradeoff"><i class="fa fa-check"></i><b>5.2.3</b> Bias-variance tradeoff</a></li>
<li class="chapter" data-level="5.2.4" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#choosing-k"><i class="fa fa-check"></i><b>5.2.4</b> Choosing <em>k</em></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#example-on-the-iris-dataset"><i class="fa fa-check"></i><b>5.3</b> Example on the Iris dataset</a></li>
<li class="chapter" data-level="5.4" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#knn-cell-segmentation"><i class="fa fa-check"></i><b>5.4</b> Classification: cell segmentation</a><ul>
<li class="chapter" data-level="5.4.1" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#cell-segmentation-data-set"><i class="fa fa-check"></i><b>5.4.1</b> Cell segmentation data set</a></li>
<li class="chapter" data-level="5.4.2" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#data-splitting"><i class="fa fa-check"></i><b>5.4.2</b> Data splitting</a></li>
<li class="chapter" data-level="5.4.3" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#identification-of-data-quality-issues"><i class="fa fa-check"></i><b>5.4.3</b> Identification of data quality issues</a></li>
<li class="chapter" data-level="5.4.4" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#fit-model"><i class="fa fa-check"></i><b>5.4.4</b> Fit model</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#knn-regression"><i class="fa fa-check"></i><b>5.5</b> Regression</a><ul>
<li class="chapter" data-level="5.5.1" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#partition-data"><i class="fa fa-check"></i><b>5.5.1</b> Partition data</a></li>
<li class="chapter" data-level="5.5.2" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#data-pre-processing"><i class="fa fa-check"></i><b>5.5.2</b> Data pre-processing</a></li>
<li class="chapter" data-level="5.5.3" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#search-for-optimum-k"><i class="fa fa-check"></i><b>5.5.3</b> Search for optimum <em>k</em></a></li>
<li class="chapter" data-level="5.5.4" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#use-model-to-make-predictions"><i class="fa fa-check"></i><b>5.5.4</b> Use model to make predictions</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="clustering.html"><a href="clustering.html#exercises"><i class="fa fa-check"></i><b>5.6</b> Exercises</a><ul>
<li class="chapter" data-level="5.6.1" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#knnEx1"><i class="fa fa-check"></i><b>5.6.1</b> Exercise 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="svm.html"><a href="svm.html"><i class="fa fa-check"></i><b>6</b> Support vector machines</a><ul>
<li class="chapter" data-level="6.1" data-path="clustering.html"><a href="clustering.html#introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="svm.html"><a href="svm.html#maximum-margin-classifier"><i class="fa fa-check"></i><b>6.1.1</b> Maximum margin classifier</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="svm.html"><a href="svm.html#support-vector-classifier"><i class="fa fa-check"></i><b>6.2</b> Support vector classifier</a></li>
<li class="chapter" data-level="6.3" data-path="svm.html"><a href="svm.html#support-vector-machine"><i class="fa fa-check"></i><b>6.3</b> Support Vector Machine</a></li>
<li class="chapter" data-level="6.4" data-path="svm.html"><a href="svm.html#example---training-a-classifier"><i class="fa fa-check"></i><b>6.4</b> Example - training a classifier</a><ul>
<li class="chapter" data-level="6.4.1" data-path="svm.html"><a href="svm.html#setup-environment"><i class="fa fa-check"></i><b>6.4.1</b> Setup environment</a></li>
<li class="chapter" data-level="6.4.2" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#partition-data"><i class="fa fa-check"></i><b>6.4.2</b> Partition data</a></li>
<li class="chapter" data-level="6.4.3" data-path="svm.html"><a href="svm.html#visualize-training-data"><i class="fa fa-check"></i><b>6.4.3</b> Visualize training data</a></li>
<li class="chapter" data-level="6.4.4" data-path="svm.html"><a href="svm.html#define-a-custom-model"><i class="fa fa-check"></i><b>6.4.4</b> Define a custom model</a></li>
<li class="chapter" data-level="6.4.5" data-path="svm.html"><a href="svm.html#model-cross-validation-and-tuning"><i class="fa fa-check"></i><b>6.4.5</b> Model cross-validation and tuning</a></li>
<li class="chapter" data-level="6.4.6" data-path="svm.html"><a href="svm.html#prediction-performance-measures"><i class="fa fa-check"></i><b>6.4.6</b> Prediction performance measures</a></li>
<li class="chapter" data-level="6.4.7" data-path="svm.html"><a href="svm.html#plot-decision-boundary"><i class="fa fa-check"></i><b>6.4.7</b> Plot decision boundary</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="svm.html"><a href="svm.html#example---regression"><i class="fa fa-check"></i><b>6.5</b> Example - regression</a></li>
<li class="chapter" data-level="6.6" data-path="svm.html"><a href="svm.html#further-reading"><i class="fa fa-check"></i><b>6.6</b> Further reading</a></li>
<li class="chapter" data-level="6.7" data-path="clustering.html"><a href="clustering.html#exercises"><i class="fa fa-check"></i><b>6.7</b> Exercises</a><ul>
<li class="chapter" data-level="6.7.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>6.7.1</b> Exercise 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="decision-trees.html"><a href="decision-trees.html"><i class="fa fa-check"></i><b>7</b> Decision trees and random forests</a><ul>
<li class="chapter" data-level="7.1" data-path="decision-trees.html"><a href="decision-trees.html#decision-trees-1"><i class="fa fa-check"></i><b>7.1</b> Decision Trees</a></li>
<li class="chapter" data-level="7.2" data-path="decision-trees.html"><a href="decision-trees.html#random-forest"><i class="fa fa-check"></i><b>7.2</b> Random Forest</a></li>
<li class="chapter" data-level="7.3" data-path="clustering.html"><a href="clustering.html#exercises"><i class="fa fa-check"></i><b>7.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="use-case-1.html"><a href="use-case-1.html"><i class="fa fa-check"></i><b>8</b> Use case 1</a><ul>
<li class="chapter" data-level="8.1" data-path="clustering.html"><a href="clustering.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="use-case-1.html"><a href="use-case-1.html#problem-automated-detection-of-malaria"><i class="fa fa-check"></i><b>8.2</b> Problem: automated detection of malaria</a></li>
<li class="chapter" data-level="8.3" data-path="use-case-1.html"><a href="use-case-1.html#challenges"><i class="fa fa-check"></i><b>8.3</b> Challenges</a></li>
<li class="chapter" data-level="8.4" data-path="use-case-1.html"><a href="use-case-1.html#getting-started"><i class="fa fa-check"></i><b>8.4</b> Getting started</a><ul>
<li class="chapter" data-level="8.4.1" data-path="use-case-1.html"><a href="use-case-1.html#load-data"><i class="fa fa-check"></i><b>8.4.1</b> Load data</a></li>
<li class="chapter" data-level="8.4.2" data-path="use-case-1.html"><a href="use-case-1.html#model-comparison"><i class="fa fa-check"></i><b>8.4.2</b> Model comparison</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="use-case-1.html"><a href="use-case-1.html#solutions"><i class="fa fa-check"></i><b>8.5</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>9</b> Linear models and matrix algebra</a><ul>
<li class="chapter" data-level="9.1" data-path="linear-models.html"><a href="linear-models.html#linear-models-1"><i class="fa fa-check"></i><b>9.1</b> Linear models</a></li>
<li class="chapter" data-level="9.2" data-path="linear-models.html"><a href="linear-models.html#matrix-algebra"><i class="fa fa-check"></i><b>9.2</b> Matrix algebra</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>10</b> Linear regression and logistic regression</a><ul>
<li class="chapter" data-level="10.1" data-path="logistic-regression.html"><a href="logistic-regression.html#regression"><i class="fa fa-check"></i><b>10.1</b> Regression</a><ul>
<li class="chapter" data-level="10.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#linear-regression"><i class="fa fa-check"></i><b>10.1.1</b> Linear regression</a></li>
<li class="chapter" data-level="10.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#polynomial-regression"><i class="fa fa-check"></i><b>10.1.2</b> Polynomial regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#distributions-of-fits"><i class="fa fa-check"></i><b>10.1.3</b> Distributions of fits</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="logistic-regression.html"><a href="logistic-regression.html#classification"><i class="fa fa-check"></i><b>10.2</b> Classification</a><ul>
<li class="chapter" data-level="10.2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-regression"><i class="fa fa-check"></i><b>10.2.1</b> Logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="logistic-regression.html"><a href="logistic-regression.html#resources"><i class="fa fa-check"></i><b>10.3</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ann.html"><a href="ann.html"><i class="fa fa-check"></i><b>11</b> Artificial neural networks</a><ul>
<li class="chapter" data-level="11.1" data-path="ann.html"><a href="ann.html#neural-networks"><i class="fa fa-check"></i><b>11.1</b> Neural Networks</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="use-case-2.html"><a href="use-case-2.html"><i class="fa fa-check"></i><b>12</b> Use case 2</a></li>
<li class="chapter" data-level="13" data-path="mlnn.html"><a href="mlnn.html"><i class="fa fa-check"></i><b>13</b> Deep Learning</a><ul>
<li class="chapter" data-level="13.1" data-path="mlnn.html"><a href="mlnn.html#multilayer-neural-networks"><i class="fa fa-check"></i><b>13.1</b> Multilayer Neural Networks</a><ul>
<li class="chapter" data-level="13.1.1" data-path="mlnn.html"><a href="mlnn.html#reading-in-images"><i class="fa fa-check"></i><b>13.1.1</b> Reading in images</a></li>
<li class="chapter" data-level="13.1.2" data-path="mlnn.html"><a href="mlnn.html#constructing-layers-in-kerasr"><i class="fa fa-check"></i><b>13.1.2</b> Constructing layers in kerasR</a></li>
<li class="chapter" data-level="13.1.3" data-path="mlnn.html"><a href="mlnn.html#rick-and-morty-classifier-using-deep-learning"><i class="fa fa-check"></i><b>13.1.3</b> Rick and Morty classifier using Deep Learning</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="mlnn.html"><a href="mlnn.html#convolutional-neural-networks"><i class="fa fa-check"></i><b>13.2</b> Convolutional neural networks</a><ul>
<li class="chapter" data-level="13.2.1" data-path="mlnn.html"><a href="mlnn.html#checking-the-models"><i class="fa fa-check"></i><b>13.2.1</b> Checking the models</a></li>
<li class="chapter" data-level="13.2.2" data-path="mlnn.html"><a href="mlnn.html#asking-more-precise-questions"><i class="fa fa-check"></i><b>13.2.2</b> Asking more precise questions</a></li>
<li class="chapter" data-level="13.2.3" data-path="mlnn.html"><a href="mlnn.html#more-complex-networks"><i class="fa fa-check"></i><b>13.2.3</b> More complex networks</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="svm.html"><a href="svm.html#further-reading"><i class="fa fa-check"></i><b>13.3</b> Further reading</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="logistic-regression.html"><a href="logistic-regression.html#resources"><i class="fa fa-check"></i><b>A</b> Resources</a><ul>
<li class="chapter" data-level="A.1" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i><b>A.1</b> Python</a></li>
<li class="chapter" data-level="A.2" data-path="resources.html"><a href="resources.html#machine-learning-data-set-repositories"><i class="fa fa-check"></i><b>A.2</b> Machine learning data set repositories</a><ul>
<li class="chapter" data-level="A.2.1" data-path="resources.html"><a href="resources.html#mldata"><i class="fa fa-check"></i><b>A.2.1</b> MLDATA</a></li>
<li class="chapter" data-level="A.2.2" data-path="resources.html"><a href="resources.html#uci-machine-learning-repository"><i class="fa fa-check"></i><b>A.2.2</b> UCI Machine Learning Repository</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="solutions-dimensionality-reduction.html"><a href="solutions-dimensionality-reduction.html"><i class="fa fa-check"></i><b>B</b> Solutions ch. 2 - Dimensionality reduction</a><ul>
<li class="chapter" data-level="B.1" data-path="solutions-dimensionality-reduction.html"><a href="solutions-dimensionality-reduction.html#exercise-2.5."><i class="fa fa-check"></i><b>B.1</b> Exercise 2.5.</a></li>
<li class="chapter" data-level="B.2" data-path="solutions-dimensionality-reduction.html"><a href="solutions-dimensionality-reduction.html#exercise-2.6."><i class="fa fa-check"></i><b>B.2</b> Exercise 2.6.</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="solutions-clustering.html"><a href="solutions-clustering.html"><i class="fa fa-check"></i><b>C</b> Solutions ch. 4 - Clustering</a><ul>
<li class="chapter" data-level="C.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>C.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="solutions-nearest-neighbours.html"><a href="solutions-nearest-neighbours.html"><i class="fa fa-check"></i><b>D</b> Solutions ch. 7 - Nearest neighbours</a><ul>
<li class="chapter" data-level="D.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>D.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="solutions-svm.html"><a href="solutions-svm.html"><i class="fa fa-check"></i><b>E</b> Solutions ch. 6 - Support vector machines</a><ul>
<li class="chapter" data-level="E.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>E.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="F" data-path="solutions-decision-trees.html"><a href="solutions-decision-trees.html"><i class="fa fa-check"></i><b>F</b> Solutions ch. 9 - Decision trees and random forests</a><ul>
<li class="chapter" data-level="F.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>F.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="G" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html"><i class="fa fa-check"></i><b>G</b> Solutions chapter 8 - use case 1</a><ul>
<li class="chapter" data-level="G.1" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#preparation"><i class="fa fa-check"></i><b>G.1</b> Preparation</a><ul>
<li class="chapter" data-level="G.1.1" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#load-required-libraries"><i class="fa fa-check"></i><b>G.1.1</b> Load required libraries</a></li>
<li class="chapter" data-level="G.1.2" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#define-svm-model"><i class="fa fa-check"></i><b>G.1.2</b> Define SVM model</a></li>
<li class="chapter" data-level="G.1.3" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#setup-parallel-processing"><i class="fa fa-check"></i><b>G.1.3</b> Setup parallel processing</a></li>
<li class="chapter" data-level="G.1.4" data-path="use-case-1.html"><a href="use-case-1.html#load-data"><i class="fa fa-check"></i><b>G.1.4</b> Load data</a></li>
</ul></li>
<li class="chapter" data-level="G.2" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#assess-data-quality"><i class="fa fa-check"></i><b>G.2</b> Assess data quality</a><ul>
<li class="chapter" data-level="G.2.1" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#zero-and-near-zero-variance-predictors"><i class="fa fa-check"></i><b>G.2.1</b> Zero and near-zero variance predictors</a></li>
<li class="chapter" data-level="G.2.2" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#are-all-predictors-on-the-same-scale"><i class="fa fa-check"></i><b>G.2.2</b> Are all predictors on the same scale?</a></li>
<li class="chapter" data-level="G.2.3" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#redundancy-from-correlated-variables"><i class="fa fa-check"></i><b>G.2.3</b> Redundancy from correlated variables</a></li>
<li class="chapter" data-level="G.2.4" data-path="nearest-neighbours.html"><a href="nearest-neighbours.html#skewness"><i class="fa fa-check"></i><b>G.2.4</b> Skewness</a></li>
</ul></li>
<li class="chapter" data-level="G.3" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#infection-status-two-class-problem"><i class="fa fa-check"></i><b>G.3</b> Infection status (two-class problem)</a><ul>
<li class="chapter" data-level="G.3.1" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#model-training-and-parameter-tuning"><i class="fa fa-check"></i><b>G.3.1</b> Model training and parameter tuning</a></li>
<li class="chapter" data-level="G.3.2" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#knn"><i class="fa fa-check"></i><b>G.3.2</b> KNN</a></li>
<li class="chapter" data-level="G.3.3" data-path="svm.html"><a href="svm.html#svm"><i class="fa fa-check"></i><b>G.3.3</b> SVM</a></li>
<li class="chapter" data-level="G.3.4" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#decision-tree"><i class="fa fa-check"></i><b>G.3.4</b> Decision tree</a></li>
<li class="chapter" data-level="G.3.5" data-path="decision-trees.html"><a href="decision-trees.html#random-forest"><i class="fa fa-check"></i><b>G.3.5</b> Random forest</a></li>
<li class="chapter" data-level="G.3.6" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#compare-models"><i class="fa fa-check"></i><b>G.3.6</b> Compare models</a></li>
<li class="chapter" data-level="G.3.7" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#predict-test-set-using-our-best-model"><i class="fa fa-check"></i><b>G.3.7</b> Predict test set using our best model</a></li>
<li class="chapter" data-level="G.3.8" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#roc-curve"><i class="fa fa-check"></i><b>G.3.8</b> ROC curve</a></li>
</ul></li>
<li class="chapter" data-level="G.4" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#discrimination-of-infective-stages-multi-class-problem"><i class="fa fa-check"></i><b>G.4</b> Discrimination of infective stages (multi-class problem)</a><ul>
<li class="chapter" data-level="G.4.1" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#define-cross-validation-procedure"><i class="fa fa-check"></i><b>G.4.1</b> Define cross-validation procedure</a></li>
<li class="chapter" data-level="G.4.2" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#knn-1"><i class="fa fa-check"></i><b>G.4.2</b> KNN</a></li>
<li class="chapter" data-level="G.4.3" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#svm-1"><i class="fa fa-check"></i><b>G.4.3</b> SVM</a></li>
<li class="chapter" data-level="G.4.4" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#decision-tree-1"><i class="fa fa-check"></i><b>G.4.4</b> Decision tree</a></li>
<li class="chapter" data-level="G.4.5" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#random-forest-1"><i class="fa fa-check"></i><b>G.4.5</b> Random forest</a></li>
<li class="chapter" data-level="G.4.6" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#compare-models-1"><i class="fa fa-check"></i><b>G.4.6</b> Compare models</a></li>
<li class="chapter" data-level="G.4.7" data-path="use-case-1-solutions.html"><a href="use-case-1-solutions.html#predict-test-set-using-our-best-model-1"><i class="fa fa-check"></i><b>G.4.7</b> Predict test set using our best model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="H" data-path="solutions-linear-models.html"><a href="solutions-linear-models.html"><i class="fa fa-check"></i><b>H</b> Solutions ch. 3 - Linear models and matrix algebra</a><ul>
<li class="chapter" data-level="H.1" data-path="solutions-linear-models.html"><a href="solutions-linear-models.html#example-2"><i class="fa fa-check"></i><b>H.1</b> Example 2</a></li>
<li class="chapter" data-level="H.2" data-path="solutions-linear-models.html"><a href="solutions-linear-models.html#example-2-1"><i class="fa fa-check"></i><b>H.2</b> Example 2</a></li>
</ul></li>
<li class="chapter" data-level="I" data-path="solutions-logistic-regression.html"><a href="solutions-logistic-regression.html"><i class="fa fa-check"></i><b>I</b> Solutions ch. 4 - Linear and non-linear (logistic) regression</a></li>
<li class="chapter" data-level="J" data-path="solutions-ann.html"><a href="solutions-ann.html"><i class="fa fa-check"></i><b>J</b> Solutions ch. 10 - Artificial neural networks</a><ul>
<li class="chapter" data-level="J.1" data-path="svm.html"><a href="svm.html#exercise-1"><i class="fa fa-check"></i><b>J.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="K" data-path="use-case-2-solutions.html"><a href="use-case-2-solutions.html"><i class="fa fa-check"></i><b>K</b> Solutions for use case 2</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Machine Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="clustering" class="section level1">
<h1><span class="header-section-number">4</span> Clustering</h1>
<!-- Matt -->
<!-- http://www.madgroup.path.cam.ac.uk/microarraysummary.shtml -->
<!--
if variables are in same units - don't standardize, otherwise standardize
-->
<div id="introduction" class="section level2">
<h2><span class="header-section-number">4.1</span> Introduction</h2>
<p>Clustering attempts to find groups (clusters) of similar objects. The members of a cluster should be more similar to each other, than to objects in other clusters. Clustering algorithms aim to minimize intra-cluster variation and maximize inter-cluster variation.</p>
<p>Methods of clustering can be broadly divided into two types:</p>
<p><strong>Hierarchic</strong> techniques produce dendrograms (trees) through a process of division or agglomeration.</p>
<p><strong>Partitioning</strong> algorithms divide objects into non-overlapping subsets (examples include k-means and DBSCAN)</p>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/clusterTypes-1.png" alt="Example clusters. **A**, *blobs*; **B**, *aggregation* [@Gionis2007]; **C**, *noisy moons*; **D**, *different density*; **E**, *anisotropic distributions*; **F**, *no structure*." width="80%" />
<p class="caption">
Example clusters. <strong>A</strong>, <em>blobs</em>; <strong>B</strong>, <em>aggregation</em> <span class="citation">(Gionis, Mannila, and Tsaparas <a href="#ref-Gionis2007">2007</a>)</span>; <strong>C</strong>, <em>noisy moons</em>; <strong>D</strong>, <em>different density</em>; <strong>E</strong>, <em>anisotropic distributions</em>; <strong>F</strong>, <em>no structure</em>.
</p>
</div>
</div>
<div id="distance-metrics" class="section level2">
<h2><span class="header-section-number">4.2</span> Distance metrics</h2>
<p>Various distance metrics can be used with clustering algorithms. We will use Euclidean distance in the examples and exercises in this chapter.</p>
<p><span class="math display" id="eq:euclidean">\[\begin{equation}
  distance\left(p,q\right)=\sqrt{\sum_{i=1}^{n} (p_i-q_i)^2}
  \tag{4.1}
\end{equation}\]</span></p>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/euclideanDistanceDiagram-1.png" alt="Euclidean distance." width="75%" />
<p class="caption">
Euclidean distance.
</p>
</div>
</div>
<div id="hierarchic-agglomerative" class="section level2">
<h2><span class="header-section-number">4.3</span> Hierarchic agglomerative</h2>
<div class="figure" style="text-align: center">
<img src="images/hclust_demo_0.png" alt="Building a dendrogram using hierarchic agglomerative clustering." width="55%" /><img src="images/hclust_demo_1.png" alt="Building a dendrogram using hierarchic agglomerative clustering." width="55%" /><img src="images/hclust_demo_2.png" alt="Building a dendrogram using hierarchic agglomerative clustering." width="55%" /><img src="images/hclust_demo_3.png" alt="Building a dendrogram using hierarchic agglomerative clustering." width="55%" /><img src="images/hclust_demo_4.png" alt="Building a dendrogram using hierarchic agglomerative clustering." width="55%" />
<p class="caption">
Building a dendrogram using hierarchic agglomerative clustering.
</p>
</div>
<div id="linkage-algorithms" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Linkage algorithms</h3>
<table>
<caption>Example distance matrix</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">A</th>
<th align="left">B</th>
<th align="left">C</th>
<th align="left">D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">B</td>
<td align="left">2</td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">C</td>
<td align="left">6</td>
<td align="left">5</td>
<td align="left"></td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">D</td>
<td align="left">10</td>
<td align="left">10</td>
<td align="left">5</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">E</td>
<td align="left">9</td>
<td align="left">8</td>
<td align="left">3</td>
<td align="left">4</td>
</tr>
</tbody>
</table>
<p>Single linkage - nearest neighbours linkage</p>
<p>Complete linkage - furthest neighbours linkage</p>
<p>Average linkage - UPGMA (Unweighted Pair Group Method with Arithmetic Mean)</p>
<!--
Explain anatomy of the dendrogram - branches, nodes and leaves.
-->
<table>
<caption>Merge distances for objects in the example distance matrix using three different linkage methods.</caption>
<thead>
<tr class="header">
<th align="left">Groups</th>
<th align="right">Single</th>
<th align="right">Complete</th>
<th align="right">Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">A,B,C,D,E</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0</td>
</tr>
<tr class="even">
<td align="left">(A,B),C,D,E</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2.0</td>
</tr>
<tr class="odd">
<td align="left">(A,B),(C,E),D</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">3.0</td>
</tr>
<tr class="even">
<td align="left">(A,B)(C,D,E)</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="right">4.5</td>
</tr>
<tr class="odd">
<td align="left">(A,B,C,D,E)</td>
<td align="right">5</td>
<td align="right">10</td>
<td align="right">8.0</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/linkageComparison-1.png" alt="Dendrograms for the example distance matrix using three different linkage methods. " width="100%" /><img src="03-clustering_files/figure-html/linkageComparison-2.png" alt="Dendrograms for the example distance matrix using three different linkage methods. " width="100%" /><img src="03-clustering_files/figure-html/linkageComparison-3.png" alt="Dendrograms for the example distance matrix using three different linkage methods. " width="100%" />
<p class="caption">
Dendrograms for the example distance matrix using three different linkage methods.
</p>
</div>
</div>
</div>
<div id="k-means" class="section level2">
<h2><span class="header-section-number">4.4</span> K-means</h2>
<div id="algorithm" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Algorithm</h3>
<p>Pseudocode for the K-means algorithm</p>
<pre><code>randomly choose k objects as initial centroids
while true:
  1. create k clusters by assigning each object to closest centroid
  2. compute k new centroids by averaging the objects in each cluster
  3. if none of the centroids differ from the previous iteration:
        return the current set of clusters</code></pre>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansIterations-1.png" alt="Iterations of the k-means algorithm" width="90%" />
<p class="caption">
Iterations of the k-means algorithm
</p>
</div>
<p>The default setting of the <strong>kmeans</strong> function is to perform a maximum of 10 iterations and if the algorithm fails to converge a warning is issued. The maximum number of iterations is set with the argument <strong>iter.max</strong>.</p>
</div>
<div id="choosing-initial-cluster-centres" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Choosing initial cluster centres</h3>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">library</span>(RColorBrewer)</a>
<a class="sourceLine" id="cb38-2" data-line-number="2">point_shapes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>)</a>
<a class="sourceLine" id="cb38-3" data-line-number="3">point_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">3</span>,<span class="st">&quot;Dark2&quot;</span>)</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">point_size =<span class="st"> </span><span class="fl">1.5</span></a>
<a class="sourceLine" id="cb38-5" data-line-number="5">center_point_size =<span class="st"> </span><span class="dv">8</span></a>
<a class="sourceLine" id="cb38-6" data-line-number="6"></a>
<a class="sourceLine" id="cb38-7" data-line-number="7">blobs &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/blobs.csv&quot;</span>, <span class="dt">header=</span>F))</a>
<a class="sourceLine" id="cb38-8" data-line-number="8"></a>
<a class="sourceLine" id="cb38-9" data-line-number="9">good_centres &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">7</span>,<span class="dv">3</span>,<span class="dv">12</span>,<span class="dv">7</span>), <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">byrow=</span>T))</a>
<a class="sourceLine" id="cb38-10" data-line-number="10">bad_centres &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">13</span>,<span class="dv">13</span>,<span class="dv">8</span>,<span class="dv">12</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">byrow=</span>T))</a>
<a class="sourceLine" id="cb38-11" data-line-number="11"></a>
<a class="sourceLine" id="cb38-12" data-line-number="12">good_result &lt;-<span class="st"> </span><span class="kw">kmeans</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">centers=</span>good_centres)</a>
<a class="sourceLine" id="cb38-13" data-line-number="13">bad_result &lt;-<span class="st"> </span><span class="kw">kmeans</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">centers=</span>bad_centres)</a>
<a class="sourceLine" id="cb38-14" data-line-number="14"></a>
<a class="sourceLine" id="cb38-15" data-line-number="15">plotList &lt;-<span class="st"> </span><span class="kw">list</span>(</a>
<a class="sourceLine" id="cb38-16" data-line-number="16"><span class="kw">ggplot</span>(blobs, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-17" data-line-number="17"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span>point_colours[good_result<span class="op">$</span>cluster], <span class="dt">shape=</span>point_shapes[good_result<span class="op">$</span>cluster], </a>
<a class="sourceLine" id="cb38-18" data-line-number="18">             <span class="dt">size=</span>point_size) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-19" data-line-number="19"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span>good_centres, <span class="kw">aes</span>(V1,V2), <span class="dt">shape=</span><span class="dv">3</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">size=</span>center_point_size) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-20" data-line-number="20"><span class="st">  </span><span class="kw">theme_bw</span>(),</a>
<a class="sourceLine" id="cb38-21" data-line-number="21"><span class="kw">ggplot</span>(blobs, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-22" data-line-number="22"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span>point_colours[bad_result<span class="op">$</span>cluster], <span class="dt">shape=</span>point_shapes[bad_result<span class="op">$</span>cluster], </a>
<a class="sourceLine" id="cb38-23" data-line-number="23">             <span class="dt">size=</span>point_size) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-24" data-line-number="24"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span>bad_centres, <span class="kw">aes</span>(V1,V2), <span class="dt">shape=</span><span class="dv">3</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">size=</span>center_point_size) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-25" data-line-number="25"><span class="st">  </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb38-26" data-line-number="26">)</a>
<a class="sourceLine" id="cb38-27" data-line-number="27"></a>
<a class="sourceLine" id="cb38-28" data-line-number="28">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb38-29" data-line-number="29">  plotList, <span class="dt">nrow=</span><span class="dv">1</span>, <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">showXAxisPlotLabels =</span> T, <span class="dt">showYAxisPlotLabels =</span> T, </a>
<a class="sourceLine" id="cb38-30" data-line-number="30">  <span class="dt">xAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb38-31" data-line-number="31">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb38-32" data-line-number="32"></a>
<a class="sourceLine" id="cb38-33" data-line-number="33">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansCentreChoice-1.png" alt="Initial centres determine clusters. The starting centres are shown as crosses. **A**, real clusters found; **B**, convergence to a local minimum." width="100%" />
<p class="caption">
Initial centres determine clusters. The starting centres are shown as crosses. <strong>A</strong>, real clusters found; <strong>B</strong>, convergence to a local minimum.
</p>
</div>
<p>Convergence to a local minimum can be avoided by starting the algorithm multiple times, with different random centres. The <strong>nstart</strong> argument to the <strong>k-means</strong> function can be used to specify the number of random sets and optimal solution will be selected automatically.</p>
</div>
<div id="choosingK" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Choosing k</h3>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">point_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">9</span>,<span class="st">&quot;Set1&quot;</span>)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2">k &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">9</span></a>
<a class="sourceLine" id="cb39-3" data-line-number="3">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb39-4" data-line-number="4"></a>
<a class="sourceLine" id="cb39-5" data-line-number="5">plotList &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){</a>
<a class="sourceLine" id="cb39-6" data-line-number="6">  <span class="kw">ggplot</span>(blobs, <span class="kw">aes</span>(V1, V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb39-7" data-line-number="7"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">col=</span>point_colours[res[[i]]<span class="op">$</span>cluster], <span class="dt">size=</span><span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-8" data-line-number="8"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">data=</span><span class="kw">as.data.frame</span>(res[[i]]<span class="op">$</span>centers), <span class="kw">aes</span>(V1,V2), <span class="dt">shape=</span><span class="dv">3</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">size=</span><span class="dv">5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-9" data-line-number="9"><span class="st">    </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x=</span><span class="dv">2</span>, <span class="dt">y=</span><span class="dv">13</span>, <span class="dt">label=</span><span class="kw">paste</span>(<span class="st">&quot;k=&quot;</span>, i, <span class="dt">sep=</span><span class="st">&quot;&quot;</span>), <span class="dt">size=</span><span class="dv">8</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb39-10" data-line-number="10"><span class="st">    </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb39-11" data-line-number="11">}</a>
<a class="sourceLine" id="cb39-12" data-line-number="12">)</a>
<a class="sourceLine" id="cb39-13" data-line-number="13"></a>
<a class="sourceLine" id="cb39-14" data-line-number="14">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb39-15" data-line-number="15">  plotList, <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">ncol=</span><span class="dv">3</span>, <span class="dt">showXAxisPlotLabels =</span> T, <span class="dt">showYAxisPlotLabels =</span> T</a>
<a class="sourceLine" id="cb39-16" data-line-number="16">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb39-17" data-line-number="17"></a>
<a class="sourceLine" id="cb39-18" data-line-number="18">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansRangeK-1.png" alt="K-means clustering of the blobs data set using a range of values of k from 1-9. Cluster centres indicated with a cross." width="100%" />
<p class="caption">
K-means clustering of the blobs data set using a range of values of k from 1-9. Cluster centres indicated with a cross.
</p>
</div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">tot_withinss &lt;-<span class="st"> </span><span class="kw">sapply</span>(k, <span class="cf">function</span>(i){res[[i]]<span class="op">$</span>tot.withinss})</a>
<a class="sourceLine" id="cb40-2" data-line-number="2"><span class="kw">qplot</span>(k, tot_withinss, <span class="dt">geom=</span><span class="kw">c</span>(<span class="st">&quot;point&quot;</span>, <span class="st">&quot;line&quot;</span>), </a>
<a class="sourceLine" id="cb40-3" data-line-number="3">      <span class="dt">ylab=</span><span class="st">&quot;Total within-cluster sum of squares&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/choosingKplot-1.png" alt="Variance within the clusters. Total within-cluster sum of squares plotted against k." width="50%" />
<p class="caption">
Variance within the clusters. Total within-cluster sum of squares plotted against k.
</p>
</div>
<p><em>N.B.</em> we have set <code>nstart=50</code> to run the algorithm 50 times, starting from different, random sets of centroids.</p>
</div>
</div>
<div id="dbscan" class="section level2">
<h2><span class="header-section-number">4.5</span> DBSCAN</h2>
<p>Density-based spatial clustering of applications with noise</p>
<div id="algorithm-1" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Algorithm</h3>
<p>Abstract DBSCAN algorithm in pseudocode <span class="citation">(Schubert et al. <a href="#ref-Schubert2017">2017</a>)</span></p>
<pre><code>1 Compute neighbours of each point and identify core points   // Identify core points
2 Join neighbouring core points into clusters                 // Assign core points
3 foreach non-core point do
      Add to a neighbouring core point if possible            // Assign border points
      Otherwise, add to noise                                 // Assign noise points</code></pre>
<div class="figure" style="text-align: center">
<img src="images/DBSCAN_Illustration.svg" alt="Illustration of the DBSCAN algorithm. By Chire (Own work) [CC BY-SA 3.0 (http://creativecommons.org/licenses/by-sa/3.0)], via Wikimedia Commons." width="75%" />
<p class="caption">
Illustration of the DBSCAN algorithm. By Chire (Own work) [CC BY-SA 3.0 (<a href="http://creativecommons.org/licenses/by-sa/3.0" class="uri">http://creativecommons.org/licenses/by-sa/3.0</a>)], via Wikimedia Commons.
</p>
</div>
<p>The method requires two parameters; MinPts that is the minimum number of samples in any cluster; Eps that is the maximum distance of the sample to at least one other sample within the same cluster.</p>
<p>This algorithm works on a parametric approach. The two parameters involved in this algorithm are:</p>
<ul>
<li>e (eps) is the radius of our neighborhoods around a data point p.</li>
<li>minPts is the minimum number of data points we want in a neighborhood to define a cluster.</li>
</ul>
</div>
<div id="implementation-in-r" class="section level3">
<h3><span class="header-section-number">4.5.2</span> Implementation in R</h3>
<p>DBSCAN is implemented in two R packages: <a href="https://cran.r-project.org/package=dbscan">dbscan</a> and <a href="https://cran.r-project.org/package=fpc">fpc</a>. We will use the package <a href="https://cran.r-project.org/package=dbscan">dbscan</a>, because it is significantly faster and can handle larger data sets than <a href="https://cran.r-project.org/package=fpc">fpc</a>. The function has the same name in both packages and so if for any reason both packages have been loaded into our current workspace, there is a danger of calling the wrong implementation. To avoid this we can specify the package name when calling the function, e.g.:</p>
<pre><code>dbscan::dbscan</code></pre>
<p>We load the dbscan package in the usual way:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1"><span class="kw">library</span>(dbscan)</a></code></pre></div>
</div>
<div id="choosing-parameters" class="section level3">
<h3><span class="header-section-number">4.5.3</span> Choosing parameters</h3>
<p>The algorithm only needs parameteres <strong>eps</strong> and <strong>minPts</strong>.</p>
<p>Read in data and use <strong>kNNdist</strong> function from <a href="https://cran.r-project.org/package=dbscan">dbscan</a> package to plot the distances of the 10-nearest neighbours for each observation (figure <a href="#fig:blobsKNNdist"><strong>??</strong></a>).</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">blobs &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/blobs.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb44-2" data-line-number="2"><span class="kw">kNNdistplot</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb44-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.6</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/blobsKNNdist-1.png" alt="10-nearest neighbour distances for the blobs data set" width="75%" />
<p class="caption">
10-nearest neighbour distances for the blobs data set
</p>
</div>
<!-- dist2knn <- kNNdist(blobs, 10) -->
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.6</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb45-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##   0   1   2   3 
##  43 484 486 487</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1"><span class="kw">ggplot</span>(blobs, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span><span class="kw">brewer.pal</span>(<span class="dv">8</span>,<span class="st">&quot;Dark2&quot;</span>)[<span class="kw">c</span>(<span class="dv">8</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>)][res<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>],</a>
<a class="sourceLine" id="cb47-3" data-line-number="3">             <span class="dt">shape=</span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>)[res<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>],</a>
<a class="sourceLine" id="cb47-4" data-line-number="4">             <span class="dt">size=</span><span class="fl">1.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb47-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/blobsDBSCANscatter-1.png" alt="DBSCAN clustering (eps=0.6, minPts=10) of the blobs data set. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering (eps=0.6, minPts=10) of the blobs data set. Outlier observations are shown as grey crosses.
</p>
</div>
</div>
</div>
<div id="example-clustering-synthetic-data-sets" class="section level2">
<h2><span class="header-section-number">4.6</span> Example: clustering synthetic data sets</h2>
<div id="hierarchic-agglomerative-1" class="section level3">
<h3><span class="header-section-number">4.6.1</span> Hierarchic agglomerative</h3>
<div id="step-by-step-instructions" class="section level4">
<h4><span class="header-section-number">4.6.1.1</span> Step-by-step instructions</h4>
<ol style="list-style-type: decimal">
<li>Load required packages.</li>
</ol>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1"><span class="kw">library</span>(RColorBrewer)</a>
<a class="sourceLine" id="cb48-2" data-line-number="2"><span class="kw">library</span>(dendextend)</a></code></pre></div>
<pre><code>## 
## ---------------------
## Welcome to dendextend version 1.13.4
## Type citation(&#39;dendextend&#39;) for how to cite the package.
## 
## Type browseVignettes(package = &#39;dendextend&#39;) for the package vignette.
## The github page is: https://github.com/talgalili/dendextend/
## 
## Suggestions and bug-reports can be submitted at: https://github.com/talgalili/dendextend/issues
## Or contact: &lt;tal.galili@gmail.com&gt;
## 
## 	To suppress this message use:  suppressPackageStartupMessages(library(dendextend))
## ---------------------</code></pre>
<pre><code>## 
## Attaching package: &#39;dendextend&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggdendro&#39;:
## 
##     theme_dendro</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     cutree</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb53-2" data-line-number="2"><span class="kw">library</span>(GGally)</a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Retrieve a palette of eight colours.</li>
</ol>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1">cluster_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>,<span class="st">&quot;Dark2&quot;</span>)</a></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Read in data for <strong>blobs</strong> example.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1">blobs &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/blobs.csv&quot;</span>, <span class="dt">header=</span>F)</a></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Create distance matrix using Euclidean distance metric.</li>
</ol>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">d &lt;-<span class="st"> </span><span class="kw">dist</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])</a></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Perform hierarchical clustering using the <strong>average</strong> agglomeration method and convert the result to an object of class <strong>dendrogram</strong>. A <strong>dendrogram</strong> object can be edited using the advanced features of the <strong>dendextend</strong> package.</li>
</ol>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" data-line-number="1">dend &lt;-<span class="st"> </span><span class="kw">as.dendrogram</span>(<span class="kw">hclust</span>(d, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>))</a></code></pre></div>
<ol start="6" style="list-style-type: decimal">
<li>Cut the tree into three clusters</li>
</ol>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">clusters &lt;-<span class="st"> </span><span class="kw">cutree</span>(dend,<span class="dv">3</span>,<span class="dt">order_clusters_as_data=</span>F)</a></code></pre></div>
<ol start="7" style="list-style-type: decimal">
<li>The vector <strong>clusters</strong> contains the cluster membership (in this case <em>1</em>, <em>2</em> or <em>3</em>) of each observation (data point) in the order they appear on the dendrogram. We can use this vector to colour the branches of the dendrogram by cluster.</li>
</ol>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1">dend &lt;-<span class="st"> </span><span class="kw">color_branches</span>(dend, <span class="dt">clusters=</span>clusters, <span class="dt">col=</span>cluster_colours[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>])</a></code></pre></div>
<ol start="8" style="list-style-type: decimal">
<li>We can use the <strong>labels</strong> function to annotate the leaves of the dendrogram. However, it is not possible to create legible labels for the 1,500 leaves in our example dendrogram, so we will set the label for each leaf to an empty string.</li>
</ol>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1"><span class="kw">labels</span>(dend) &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">&quot;&quot;</span>, <span class="kw">length</span>(blobs[,<span class="dv">1</span>]))</a></code></pre></div>
<ol start="9" style="list-style-type: decimal">
<li>If we want to plot the dendrogram using <strong>ggplot</strong>, we must convert it to an object of class <strong>ggdend</strong>.</li>
</ol>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1">ggd &lt;-<span class="st"> </span><span class="kw">as.ggdend</span>(dend)</a></code></pre></div>
<ol start="10" style="list-style-type: decimal">
<li>The <strong>nodes</strong> attribute of <strong>ggd</strong> is a data.frame of parameters related to the plotting of dendogram nodes. The <strong>nodes</strong> data.frame contains some NAs which will generate warning messages when <strong>ggd</strong> is processed by <strong>ggplot</strong>. Since we are not interested in annotating dendrogram nodes, the easiest option here is to delete all of the rows of <strong>nodes</strong>.</li>
</ol>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1">ggd<span class="op">$</span>nodes &lt;-<span class="st"> </span>ggd<span class="op">$</span>nodes[<span class="op">!</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(ggd<span class="op">$</span>nodes[,<span class="dv">1</span>])),]</a></code></pre></div>
<ol start="11" style="list-style-type: decimal">
<li>We can use the cluster membership of each observation contained in the vector <strong>clusters</strong> to assign colours to the data points of a scatterplot. However, first we need to reorder the vector so that the cluster memberships are in the same order that the observations appear in the data.frame of observations. Fortunately the names of the elements of the vector are the indices of the observations in the data.frame and so reordering can be accomplished in one line.</li>
</ol>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" data-line-number="1">clusters &lt;-<span class="st"> </span>clusters[<span class="kw">order</span>(<span class="kw">as.numeric</span>(<span class="kw">names</span>(clusters)))]</a></code></pre></div>
<ol start="12" style="list-style-type: decimal">
<li>We are now ready to plot a dendrogram and scatterplot. We will use the <strong>ggmatrix</strong> function from the <strong>GGally</strong> package to place the plots side-by-side.</li>
</ol>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">plotList &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">ggplot</span>(ggd),</a>
<a class="sourceLine" id="cb64-2" data-line-number="2">                 <span class="kw">ggplot</span>(blobs, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-3" data-line-number="3"><span class="st">                   </span><span class="kw">geom_point</span>(<span class="dt">col=</span>cluster_colours[clusters], <span class="dt">size=</span><span class="fl">0.2</span>)</a>
<a class="sourceLine" id="cb64-4" data-line-number="4">                 )</a>
<a class="sourceLine" id="cb64-5" data-line-number="5"></a>
<a class="sourceLine" id="cb64-6" data-line-number="6">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb64-7" data-line-number="7">  plotList, <span class="dt">nrow=</span><span class="dv">1</span>, <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">showXAxisPlotLabels =</span> F, <span class="dt">showYAxisPlotLabels =</span> F, </a>
<a class="sourceLine" id="cb64-8" data-line-number="8">  <span class="dt">xAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;dendrogram&quot;</span>, <span class="st">&quot;scatter plot&quot;</span>)</a>
<a class="sourceLine" id="cb64-9" data-line-number="9">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb64-10" data-line-number="10"></a>
<a class="sourceLine" id="cb64-11" data-line-number="11">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/hclustBlobs-1.png" alt="Hierarchical clustering of the blobs data set." width="80%" />
<p class="caption">
Hierarchical clustering of the blobs data set.
</p>
</div>
</div>
<div id="clustering-of-other-synthetic-data-sets" class="section level4">
<h4><span class="header-section-number">4.6.1.2</span> Clustering of other synthetic data sets</h4>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1">aggregation &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/example_clusters/aggregation.txt&quot;</span>)</a>
<a class="sourceLine" id="cb65-2" data-line-number="2">noisy_moons &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/noisy_moons.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb65-3" data-line-number="3">diff_density &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/different_density.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb65-4" data-line-number="4">aniso &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/aniso.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb65-5" data-line-number="5">no_structure &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/no_structure.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb65-6" data-line-number="6"></a>
<a class="sourceLine" id="cb65-7" data-line-number="7">hclust_plots &lt;-<span class="st"> </span><span class="cf">function</span>(data_set, n){</a>
<a class="sourceLine" id="cb65-8" data-line-number="8">  d &lt;-<span class="st"> </span><span class="kw">dist</span>(data_set[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])</a>
<a class="sourceLine" id="cb65-9" data-line-number="9">  dend &lt;-<span class="st"> </span><span class="kw">as.dendrogram</span>(<span class="kw">hclust</span>(d, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>))</a>
<a class="sourceLine" id="cb65-10" data-line-number="10">  clusters &lt;-<span class="st"> </span><span class="kw">cutree</span>(dend,n,<span class="dt">order_clusters_as_data=</span>F)</a>
<a class="sourceLine" id="cb65-11" data-line-number="11">  dend &lt;-<span class="st"> </span><span class="kw">color_branches</span>(dend, <span class="dt">clusters=</span>clusters, <span class="dt">col=</span>cluster_colours[<span class="dv">1</span><span class="op">:</span>n])</a>
<a class="sourceLine" id="cb65-12" data-line-number="12">  clusters &lt;-<span class="st"> </span>clusters[<span class="kw">order</span>(<span class="kw">as.numeric</span>(<span class="kw">names</span>(clusters)))]</a>
<a class="sourceLine" id="cb65-13" data-line-number="13">  <span class="kw">labels</span>(dend) &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="st">&quot;&quot;</span>, <span class="kw">length</span>(data_set[,<span class="dv">1</span>]))</a>
<a class="sourceLine" id="cb65-14" data-line-number="14">  ggd &lt;-<span class="st"> </span><span class="kw">as.ggdend</span>(dend)</a>
<a class="sourceLine" id="cb65-15" data-line-number="15">  ggd<span class="op">$</span>nodes &lt;-<span class="st"> </span>ggd<span class="op">$</span>nodes[<span class="op">!</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(ggd<span class="op">$</span>nodes[,<span class="dv">1</span>])),]</a>
<a class="sourceLine" id="cb65-16" data-line-number="16">  plotPair &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">ggplot</span>(ggd),</a>
<a class="sourceLine" id="cb65-17" data-line-number="17">    <span class="kw">ggplot</span>(data_set, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb65-18" data-line-number="18"><span class="st">      </span><span class="kw">geom_point</span>(<span class="dt">col=</span>cluster_colours[clusters], <span class="dt">size=</span><span class="fl">0.2</span>))</a>
<a class="sourceLine" id="cb65-19" data-line-number="19">  <span class="kw">return</span>(plotPair)</a>
<a class="sourceLine" id="cb65-20" data-line-number="20">}</a>
<a class="sourceLine" id="cb65-21" data-line-number="21"></a>
<a class="sourceLine" id="cb65-22" data-line-number="22">plotList &lt;-<span class="st"> </span><span class="kw">c</span>(</a>
<a class="sourceLine" id="cb65-23" data-line-number="23">  <span class="kw">hclust_plots</span>(aggregation, <span class="dv">7</span>),</a>
<a class="sourceLine" id="cb65-24" data-line-number="24">  <span class="kw">hclust_plots</span>(noisy_moons, <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb65-25" data-line-number="25">  <span class="kw">hclust_plots</span>(diff_density, <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb65-26" data-line-number="26">  <span class="kw">hclust_plots</span>(aniso, <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb65-27" data-line-number="27">  <span class="kw">hclust_plots</span>(no_structure, <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb65-28" data-line-number="28">)</a>
<a class="sourceLine" id="cb65-29" data-line-number="29"></a>
<a class="sourceLine" id="cb65-30" data-line-number="30">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb65-31" data-line-number="31">  plotList, <span class="dt">nrow=</span><span class="dv">5</span>, <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">showXAxisPlotLabels =</span> F, <span class="dt">showYAxisPlotLabels =</span> F,</a>
<a class="sourceLine" id="cb65-32" data-line-number="32">  <span class="dt">xAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;dendrogram&quot;</span>, <span class="st">&quot;scatter plot&quot;</span>), </a>
<a class="sourceLine" id="cb65-33" data-line-number="33">  <span class="dt">yAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;aggregation&quot;</span>, <span class="st">&quot;noisy moons&quot;</span>, <span class="st">&quot;different density&quot;</span>, <span class="st">&quot;anisotropic&quot;</span>, <span class="st">&quot;no structure&quot;</span>)</a>
<a class="sourceLine" id="cb65-34" data-line-number="34">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb65-35" data-line-number="35"></a>
<a class="sourceLine" id="cb65-36" data-line-number="36">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/hclustToyData-1.png" alt="Hierarchical clustering of synthetic data-sets. " width="75%" />
<p class="caption">
Hierarchical clustering of synthetic data-sets.
</p>
</div>
</div>
</div>
<div id="k-means-1" class="section level3">
<h3><span class="header-section-number">4.6.2</span> K-means</h3>
<p>Earlier we saw how k-means performed on the blobs data set. Let’s see how k-means performs on the other toy data sets. First we will define some variables and functions we will use in the analysis of all data sets.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1">k=<span class="dv">1</span><span class="op">:</span><span class="dv">9</span></a>
<a class="sourceLine" id="cb66-2" data-line-number="2">point_shapes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb66-3" data-line-number="3">point_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">7</span>,<span class="st">&quot;Dark2&quot;</span>)</a>
<a class="sourceLine" id="cb66-4" data-line-number="4">point_size =<span class="st"> </span><span class="fl">1.5</span></a>
<a class="sourceLine" id="cb66-5" data-line-number="5">center_point_size =<span class="st"> </span><span class="dv">8</span></a>
<a class="sourceLine" id="cb66-6" data-line-number="6"></a>
<a class="sourceLine" id="cb66-7" data-line-number="7">plot_tot_withinss &lt;-<span class="st"> </span><span class="cf">function</span>(kmeans_output){</a>
<a class="sourceLine" id="cb66-8" data-line-number="8">  tot_withinss &lt;-<span class="st"> </span><span class="kw">sapply</span>(k, <span class="cf">function</span>(i){kmeans_output[[i]]<span class="op">$</span>tot.withinss})</a>
<a class="sourceLine" id="cb66-9" data-line-number="9">  <span class="kw">qplot</span>(k, tot_withinss, <span class="dt">geom=</span><span class="kw">c</span>(<span class="st">&quot;point&quot;</span>, <span class="st">&quot;line&quot;</span>), </a>
<a class="sourceLine" id="cb66-10" data-line-number="10">        <span class="dt">ylab=</span><span class="st">&quot;Total within-cluster sum of squares&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb66-11" data-line-number="11">}</a>
<a class="sourceLine" id="cb66-12" data-line-number="12"></a>
<a class="sourceLine" id="cb66-13" data-line-number="13">plot_clusters &lt;-<span class="st"> </span><span class="cf">function</span>(data_set, kmeans_output, num_clusters){</a>
<a class="sourceLine" id="cb66-14" data-line-number="14">    <span class="kw">ggplot</span>(data_set, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-15" data-line-number="15"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">col=</span>point_colours[kmeans_output[[num_clusters]]<span class="op">$</span>cluster],</a>
<a class="sourceLine" id="cb66-16" data-line-number="16">               <span class="dt">shape=</span>point_shapes[kmeans_output[[num_clusters]]<span class="op">$</span>cluster], </a>
<a class="sourceLine" id="cb66-17" data-line-number="17">               <span class="dt">size=</span>point_size) <span class="op">+</span></a>
<a class="sourceLine" id="cb66-18" data-line-number="18"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">data=</span><span class="kw">as.data.frame</span>(kmeans_output[[num_clusters]]<span class="op">$</span>centers), <span class="kw">aes</span>(V1,V2),</a>
<a class="sourceLine" id="cb66-19" data-line-number="19">               <span class="dt">shape=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="st">&quot;black&quot;</span>,<span class="dt">size=</span>center_point_size) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb66-20" data-line-number="20"><span class="st">    </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb66-21" data-line-number="21">}</a></code></pre></div>
<div id="aggregation" class="section level4">
<h4><span class="header-section-number">4.6.2.1</span> Aggregation</h4>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1">aggregation &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">read.table</span>(<span class="st">&quot;data/example_clusters/aggregation.txt&quot;</span>))</a>
<a class="sourceLine" id="cb67-2" data-line-number="2">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(aggregation[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb67-3" data-line-number="3"><span class="kw">plot_tot_withinss</span>(res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansAggregationElbow-1.png" alt="K-means clustering of the aggregation data set: variance within clusters." width="50%" />
<p class="caption">
K-means clustering of the aggregation data set: variance within clusters.
</p>
</div>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1">plotList &lt;-<span class="st"> </span><span class="kw">list</span>(</a>
<a class="sourceLine" id="cb68-2" data-line-number="2">  <span class="kw">plot_clusters</span>(aggregation, res, <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb68-3" data-line-number="3">  <span class="kw">plot_clusters</span>(aggregation, res, <span class="dv">7</span>)</a>
<a class="sourceLine" id="cb68-4" data-line-number="4">)</a>
<a class="sourceLine" id="cb68-5" data-line-number="5">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb68-6" data-line-number="6">  plotList, <span class="dt">nrow=</span><span class="dv">1</span>, <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">showXAxisPlotLabels =</span> T, <span class="dt">showYAxisPlotLabels =</span> T, </a>
<a class="sourceLine" id="cb68-7" data-line-number="7">  <span class="dt">xAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;k=3&quot;</span>, <span class="st">&quot;k=7&quot;</span>)</a>
<a class="sourceLine" id="cb68-8" data-line-number="8">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb68-9" data-line-number="9">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansAggregationScatter-1.png" alt="K-means clustering of the aggregation data set: scatterplots of clusters for k=3 and k=7. Cluster centres indicated with a cross." width="100%" />
<p class="caption">
K-means clustering of the aggregation data set: scatterplots of clusters for k=3 and k=7. Cluster centres indicated with a cross.
</p>
</div>
</div>
<div id="noisy-moons" class="section level4">
<h4><span class="header-section-number">4.6.2.2</span> Noisy moons</h4>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1">noisy_moons &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/noisy_moons.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb69-2" data-line-number="2">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(noisy_moons[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb69-3" data-line-number="3"><span class="kw">plot_tot_withinss</span>(res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansNoisyMoonsElbow-1.png" alt="K-means clustering of the noisy moons data set: variance within clusters." width="50%" />
<p class="caption">
K-means clustering of the noisy moons data set: variance within clusters.
</p>
</div>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">plot_clusters</span>(noisy_moons, res, <span class="dv">2</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansNoisyMoonsScatter-1.png" alt="K-means clustering of the noisy moons data set: scatterplot of clusters for k=2. Cluster centres indicated with a cross." width="50%" />
<p class="caption">
K-means clustering of the noisy moons data set: scatterplot of clusters for k=2. Cluster centres indicated with a cross.
</p>
</div>
</div>
<div id="different-density" class="section level4">
<h4><span class="header-section-number">4.6.2.3</span> Different density</h4>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1">diff_density &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/different_density.csv&quot;</span>, <span class="dt">header=</span>F))</a>
<a class="sourceLine" id="cb71-2" data-line-number="2">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(diff_density[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a></code></pre></div>
<pre><code>## Warning: did not converge in 10 iterations

## Warning: did not converge in 10 iterations

## Warning: did not converge in 10 iterations

## Warning: did not converge in 10 iterations</code></pre>
<p>Failure to converge, so increase number of iterations.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(diff_density[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">iter.max=</span><span class="dv">20</span>, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb73-2" data-line-number="2"><span class="kw">plot_tot_withinss</span>(res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansDiffDensityElbow-1.png" alt="K-means clustering of the different density distributions data set: variance within clusters." width="50%" />
<p class="caption">
K-means clustering of the different density distributions data set: variance within clusters.
</p>
</div>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1"><span class="kw">plot_clusters</span>(diff_density, res, <span class="dv">2</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansDiffDensityScatter-1.png" alt="K-means clustering of the different density distributions data set: scatterplots of clusters for k=2 and k=3. Cluster centres indicated with a cross." width="50%" />
<p class="caption">
K-means clustering of the different density distributions data set: scatterplots of clusters for k=2 and k=3. Cluster centres indicated with a cross.
</p>
</div>
</div>
<div id="anisotropic-distributions" class="section level4">
<h4><span class="header-section-number">4.6.2.4</span> Anisotropic distributions</h4>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" data-line-number="1">aniso &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/aniso.csv&quot;</span>, <span class="dt">header=</span>F))</a>
<a class="sourceLine" id="cb75-2" data-line-number="2">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(aniso[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb75-3" data-line-number="3"><span class="kw">plot_tot_withinss</span>(res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansAnisoElbow-1.png" alt="K-means clustering  of the anisotropic distributions data set: variance within clusters." width="50%" />
<p class="caption">
K-means clustering of the anisotropic distributions data set: variance within clusters.
</p>
</div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1">plotList &lt;-<span class="st"> </span><span class="kw">list</span>(</a>
<a class="sourceLine" id="cb76-2" data-line-number="2">  <span class="kw">plot_clusters</span>(aniso, res, <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb76-3" data-line-number="3">  <span class="kw">plot_clusters</span>(aniso, res, <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb76-4" data-line-number="4">)</a>
<a class="sourceLine" id="cb76-5" data-line-number="5">pm &lt;-<span class="st"> </span><span class="kw">ggmatrix</span>(</a>
<a class="sourceLine" id="cb76-6" data-line-number="6">  plotList, <span class="dt">nrow=</span><span class="dv">1</span>, <span class="dt">ncol=</span><span class="dv">2</span>, <span class="dt">showXAxisPlotLabels =</span> T, </a>
<a class="sourceLine" id="cb76-7" data-line-number="7">  <span class="dt">showYAxisPlotLabels =</span> T, <span class="dt">xAxisLabels=</span><span class="kw">c</span>(<span class="st">&quot;k=2&quot;</span>, <span class="st">&quot;k=3&quot;</span>)</a>
<a class="sourceLine" id="cb76-8" data-line-number="8">) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb76-9" data-line-number="9">pm</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/kmeansAnisoScatter-1.png" alt="K-means clustering of the anisotropic distributions data set: scatterplots of clusters for k=2 and k=3. Cluster centres indicated with a cross." width="100%" />
<p class="caption">
K-means clustering of the anisotropic distributions data set: scatterplots of clusters for k=2 and k=3. Cluster centres indicated with a cross.
</p>
</div>
</div>
<div id="no-structure" class="section level4">
<h4><span class="header-section-number">4.6.2.5</span> No structure</h4>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1">no_structure &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/no_structure.csv&quot;</span>, <span class="dt">header=</span>F))</a>
<a class="sourceLine" id="cb77-2" data-line-number="2">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(no_structure[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a>
<a class="sourceLine" id="cb77-3" data-line-number="3"><span class="kw">plot_tot_withinss</span>(res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/noStructureElbow-1.png" alt="K-means clustering of the data set with no structure: variance within clusters." width="50%" />
<p class="caption">
K-means clustering of the data set with no structure: variance within clusters.
</p>
</div>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" data-line-number="1"><span class="kw">plot_clusters</span>(no_structure, res, <span class="dv">4</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/noStructureScatter-1.png" alt="K-means clustering of the data set with no structure: scatterplot of clusters for k=4. Cluster centres indicated with a cross." width="50%" />
<p class="caption">
K-means clustering of the data set with no structure: scatterplot of clusters for k=4. Cluster centres indicated with a cross.
</p>
</div>
</div>
</div>
<div id="dbscan-1" class="section level3">
<h3><span class="header-section-number">4.6.3</span> DBSCAN</h3>
<p>Prepare by defining some variables and a plotting function.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" data-line-number="1">point_shapes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">0</span>,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb79-2" data-line-number="2">point_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">8</span>,<span class="st">&quot;Dark2&quot;</span>)[<span class="kw">c</span>(<span class="dv">8</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>)]</a>
<a class="sourceLine" id="cb79-3" data-line-number="3">point_size =<span class="st"> </span><span class="fl">1.5</span></a>
<a class="sourceLine" id="cb79-4" data-line-number="4">center_point_size =<span class="st"> </span><span class="dv">8</span></a>
<a class="sourceLine" id="cb79-5" data-line-number="5"></a>
<a class="sourceLine" id="cb79-6" data-line-number="6">plot_dbscan_clusters &lt;-<span class="st"> </span><span class="cf">function</span>(data_set, dbscan_output){</a>
<a class="sourceLine" id="cb79-7" data-line-number="7">  <span class="kw">ggplot</span>(data_set, <span class="kw">aes</span>(V1,V2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb79-8" data-line-number="8"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">col=</span>point_colours[dbscan_output<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>],</a>
<a class="sourceLine" id="cb79-9" data-line-number="9">               <span class="dt">shape=</span>point_shapes[dbscan_output<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>], </a>
<a class="sourceLine" id="cb79-10" data-line-number="10">               <span class="dt">size=</span>point_size) <span class="op">+</span></a>
<a class="sourceLine" id="cb79-11" data-line-number="11"><span class="st">    </span><span class="kw">theme_bw</span>()</a>
<a class="sourceLine" id="cb79-12" data-line-number="12">}</a></code></pre></div>
<div id="aggregation-1" class="section level4">
<h4><span class="header-section-number">4.6.3.1</span> Aggregation</h4>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" data-line-number="1">aggregation &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/example_clusters/aggregation.txt&quot;</span>)</a>
<a class="sourceLine" id="cb80-2" data-line-number="2"><span class="kw">kNNdistplot</span>(aggregation[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb80-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">1.8</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/aggregationKNNdist-1.png" alt="10-nearest neighbour distances for the aggregation data set" width="75%" />
<p class="caption">
10-nearest neighbour distances for the aggregation data set
</p>
</div>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(aggregation[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">1.8</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb81-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##   0   1   2   3   4   5   6 
##   2 168 307 105 127  45  34</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" data-line-number="1"><span class="kw">plot_dbscan_clusters</span>(aggregation, res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/aggregationDBSCANscatter-1.png" alt="DBSCAN clustering (eps=1.8, minPts=10) of the aggregation data set. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering (eps=1.8, minPts=10) of the aggregation data set. Outlier observations are shown as grey crosses.
</p>
</div>
</div>
<div id="noisy-moons-1" class="section level4">
<h4><span class="header-section-number">4.6.3.2</span> Noisy moons</h4>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" data-line-number="1">noisy_moons &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/noisy_moons.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb84-2" data-line-number="2"><span class="kw">kNNdistplot</span>(noisy_moons[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb84-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.075</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/noisyMoonsKNNdist-1.png" alt="10-nearest neighbour distances for the noisy moons data set" width="75%" />
<p class="caption">
10-nearest neighbour distances for the noisy moons data set
</p>
</div>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(noisy_moons[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.075</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb85-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##   0   1   2 
##   8 748 744</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" data-line-number="1"><span class="kw">plot_dbscan_clusters</span>(noisy_moons, res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/noisyMoonsDBSCANscatter-1.png" alt="DBSCAN clustering (eps=0.075, minPts=10) of the noisy moons data set. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering (eps=0.075, minPts=10) of the noisy moons data set. Outlier observations are shown as grey crosses.
</p>
</div>
</div>
<div id="different-density-1" class="section level4">
<h4><span class="header-section-number">4.6.3.3</span> Different density</h4>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" data-line-number="1">diff_density &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/different_density.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb88-2" data-line-number="2"><span class="kw">kNNdistplot</span>(diff_density[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb88-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.9</span>)</a>
<a class="sourceLine" id="cb88-4" data-line-number="4"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.6</span>, <span class="dt">lty=</span><span class="dv">2</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/diffDensityKNNdist-1.png" alt="10-nearest neighbour distances for the different density distributions data set" width="75%" />
<p class="caption">
10-nearest neighbour distances for the different density distributions data set
</p>
</div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(diff_density[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.9</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb89-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##    0    1 
##   40 1460</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" data-line-number="1"><span class="kw">plot_dbscan_clusters</span>(diff_density, res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/diffDensityDBSCANscatter1-1.png" alt="DBSCAN clustering of the different density distribution data set with eps=0.9 and minPts=10. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering of the different density distribution data set with eps=0.9 and minPts=10. Outlier observations are shown as grey crosses.
</p>
</div>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(diff_density[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.6</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb92-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##   0   1   2 
## 109 399 992</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" data-line-number="1"><span class="kw">plot_dbscan_clusters</span>(diff_density, res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/diffDensityDBSCANscatter2-1.png" alt="DBSCAN clustering of the different density distribution data set with eps=0.6 and minPts=10. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering of the different density distribution data set with eps=0.6 and minPts=10. Outlier observations are shown as grey crosses.
</p>
</div>
</div>
<div id="anisotropic-distributions-1" class="section level4">
<h4><span class="header-section-number">4.6.3.4</span> Anisotropic distributions</h4>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" data-line-number="1">aniso &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/aniso.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb95-2" data-line-number="2"><span class="kw">kNNdistplot</span>(aniso[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb95-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.35</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/anisoKNNdist-1.png" alt="10-nearest neighbour distances for the anisotropic distributions data set" width="75%" />
<p class="caption">
10-nearest neighbour distances for the anisotropic distributions data set
</p>
</div>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(aniso[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.35</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb96-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##   0   1   2   3 
##  29 489 488 494</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" data-line-number="1"><span class="kw">plot_dbscan_clusters</span>(aniso, res)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/anisoDBSCANscatter-1.png" alt="DBSCAN clustering (eps=0.3, minPts=10) of the anisotropic distributions data set. Outlier observations are shown as grey crosses." width="60%" />
<p class="caption">
DBSCAN clustering (eps=0.3, minPts=10) of the anisotropic distributions data set. Outlier observations are shown as grey crosses.
</p>
</div>
</div>
<div id="no-structure-1" class="section level4">
<h4><span class="header-section-number">4.6.3.5</span> No structure</h4>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" data-line-number="1">no_structure &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/example_clusters/no_structure.csv&quot;</span>, <span class="dt">header=</span>F)</a>
<a class="sourceLine" id="cb99-2" data-line-number="2"><span class="kw">kNNdistplot</span>(no_structure[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">k=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb99-3" data-line-number="3"><span class="kw">abline</span>(<span class="dt">h=</span><span class="fl">0.057</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/noStructureKNNdist-1.png" alt="10-nearest neighbour distances for the data set with no structure." width="75%" />
<p class="caption">
10-nearest neighbour distances for the data set with no structure.
</p>
</div>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(no_structure[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.57</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb100-2" data-line-number="2"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##    1 
## 1500</code></pre>
<!--No need for scatter plot-->
</div>
</div>
</div>
<div id="evaluating-cluster-quality" class="section level2">
<h2><span class="header-section-number">4.7</span> Evaluating cluster quality</h2>
<!--
http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html
-->
<div id="silhouetteMethod" class="section level3">
<h3><span class="header-section-number">4.7.1</span> Silhouette method</h3>
<p><strong>Silhouette</strong>
<span class="math display" id="eq:silhouette">\[\begin{equation}
  s(i) = \frac{b(i) - a(i)}{max\left(a(i),b(i)\right)}
  \tag{4.2}
\end{equation}\]</span></p>
<p>Where</p>
<ul>
<li><em>a(i)</em> - average dissimmilarity of <em>i</em> with all other data within the cluster. <em>a(i)</em> can be interpreted as how well <em>i</em> is assigned to its cluster (the smaller the value, the better the assignment).</li>
<li><em>b(i)</em> - the lowest average dissimilarity of <em>i</em> to any other cluster, of which <em>i</em> is not a member.</li>
</ul>
<p>Observations with a large <em>s(i)</em> (close to 1) are very well clustered. Observations lying between clusters will have a small <em>s(i)</em> (close to 0). If an observation has a negative <em>s(i)</em>, it has probably been placed in the wrong cluster.</p>
</div>
<div id="example---k-means-clustering-of-blobs-data-set" class="section level3">
<h3><span class="header-section-number">4.7.2</span> Example - k-means clustering of blobs data set</h3>
<p>Load library required for calculating silhouette coefficients and plotting silhouettes.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" data-line-number="1"><span class="kw">library</span>(cluster)</a></code></pre></div>
<p>We are going to take another look at k-means clustering of the blobs data-set (figure <a href="#fig:kmeansRangeK"><strong>??</strong></a>). Specifically we are going to see if silhouette analysis supports our original choice of k=3 as the optimum number of clusters (figure <a href="#fig:choosingKplot"><strong>??</strong></a>).</p>
<p>Silhouette analysis requires a minimum of two clusters, so we’ll try values of k from 2 to 9.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" data-line-number="1">k &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">:</span><span class="dv">9</span></a></code></pre></div>
<p>Create a palette of colours for plotting.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" data-line-number="1">kColours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">9</span>,<span class="st">&quot;Set1&quot;</span>)</a></code></pre></div>
<p>Perform k-means clustering for each value of k from 2 to 9.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" data-line-number="1">res &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">kmeans</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], i, <span class="dt">nstart=</span><span class="dv">50</span>)})</a></code></pre></div>
<p>Calculate the Euclidean distance matrix</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" data-line-number="1">d &lt;-<span class="st"> </span><span class="kw">dist</span>(blobs[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])</a></code></pre></div>
<p>Silhouette plot for k=2</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" data-line-number="1">s2 &lt;-<span class="st"> </span><span class="kw">silhouette</span>(res[[<span class="dv">2-1</span>]]<span class="op">$</span>cluster, d)</a>
<a class="sourceLine" id="cb107-2" data-line-number="2"><span class="kw">plot</span>(s2, <span class="dt">border=</span><span class="ot">NA</span>, <span class="dt">col=</span>kColours[<span class="kw">sort</span>(res[[<span class="dv">2-1</span>]]<span class="op">$</span>cluster)], <span class="dt">main=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/silhouetteK2-1.png" alt="Silhouette plot for k-means clustering of the blobs data set with k=2." width="60%" />
<p class="caption">
Silhouette plot for k-means clustering of the blobs data set with k=2.
</p>
</div>
<p>Silhouette plot for k=9</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" data-line-number="1">s9 &lt;-<span class="st"> </span><span class="kw">silhouette</span>(res[[<span class="dv">9-1</span>]]<span class="op">$</span>cluster, d)</a>
<a class="sourceLine" id="cb108-2" data-line-number="2"><span class="kw">plot</span>(s9, <span class="dt">border=</span><span class="ot">NA</span>, <span class="dt">col=</span>kColours[<span class="kw">sort</span>(res[[<span class="dv">9-1</span>]]<span class="op">$</span>cluster)], <span class="dt">main=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/silhouetteK9-1.png" alt="Silhouette plot for k-means clustering of the blobs data set with k=9." width="60%" />
<p class="caption">
Silhouette plot for k-means clustering of the blobs data set with k=9.
</p>
</div>
<p>Let’s take a look at the silhouette plot for k=3.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" data-line-number="1">s3 &lt;-<span class="st"> </span><span class="kw">silhouette</span>(res[[<span class="dv">3-1</span>]]<span class="op">$</span>cluster, d)</a>
<a class="sourceLine" id="cb109-2" data-line-number="2"><span class="kw">plot</span>(s3, <span class="dt">border=</span><span class="ot">NA</span>, <span class="dt">col=</span>kColours[<span class="kw">sort</span>(res[[<span class="dv">3-1</span>]]<span class="op">$</span>cluster)], <span class="dt">main=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/silhouetteK3-1.png" alt="Silhouette plot for k-means clustering of the blobs data set with k=3." width="60%" />
<p class="caption">
Silhouette plot for k-means clustering of the blobs data set with k=3.
</p>
</div>
<p>So far the silhouette plots have shown that k=3 appears to be the optimum number of clusters, but we should investigate the silhouette coefficients at other values of k. Rather than produce a silhouette plot for each value of k, we can get a useful summary by making a barplot of average silhouette coefficients.</p>
<p>First we will calculate the silhouette coefficient for every observation (we need to index our list of <strong>kmeans</strong> outputs by <code>i-1</code>, because we are counting from k=2 ).</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" data-line-number="1">s &lt;-<span class="st"> </span><span class="kw">lapply</span>(k, <span class="cf">function</span>(i){<span class="kw">silhouette</span>(res[[i<span class="dv">-1</span>]]<span class="op">$</span>cluster, d)})</a></code></pre></div>
<p>We can then calculate the mean silhouette coefficient for each value of k from 2 to 9.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" data-line-number="1">avgS &lt;-<span class="st"> </span><span class="kw">sapply</span>(s, <span class="cf">function</span>(x){<span class="kw">mean</span>(x[,<span class="dv">3</span>])})</a></code></pre></div>
<p>Now we have the data we need to produce a barplot.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" data-line-number="1">dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(k, avgS)</a>
<a class="sourceLine" id="cb112-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="dt">data=</span>dat, <span class="kw">aes</span>(<span class="dt">x=</span>k, <span class="dt">y=</span>avgS)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb112-3" data-line-number="3"><span class="st">         </span><span class="kw">geom_bar</span>(<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="dt">fill=</span><span class="st">&quot;steelblue&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb112-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label=</span><span class="kw">round</span>(avgS,<span class="dv">2</span>)), <span class="dt">vjust=</span><span class="fl">1.6</span>, <span class="dt">color=</span><span class="st">&quot;white&quot;</span>, <span class="dt">size=</span><span class="fl">3.5</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb112-5" data-line-number="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&quot;Average silhouette coefficient&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb112-6" data-line-number="6"><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="dv">2</span><span class="op">:</span><span class="dv">9</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb112-7" data-line-number="7"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/silhouetteAllK-1.png" alt="Barplot of the average silhouette coefficients resulting from k-means clustering of the blobs data-set using values of k from 1-9." width="75%" />
<p class="caption">
Barplot of the average silhouette coefficients resulting from k-means clustering of the blobs data-set using values of k from 1-9.
</p>
</div>
<p>The bar plot (figure <a href="#fig:silhouetteAllK"><strong>??</strong></a>) confirms that the optimum number of clusters is three.</p>
</div>
<div id="example---dbscan-clustering-of-noisy-moons" class="section level3">
<h3><span class="header-section-number">4.7.3</span> Example - DBSCAN clustering of noisy moons</h3>
<!--
Read data

```r
noisy_moons <- read.csv("data/example_clusters/noisy_moons.csv", header=F)
```
-->
<p>The clusters that DBSCAN found in the noisy moons data set are shown in figure <a href="#fig:noisyMoonsDBSCANscatter"><strong>??</strong></a>.</p>
<p>Let’s repeat clustering, because the original result is no longer in memory.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" data-line-number="1">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(noisy_moons[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">eps=</span><span class="fl">0.075</span>, <span class="dt">minPts =</span> <span class="dv">10</span>)</a></code></pre></div>
<p>Identify noise points as we do not want to include these in the silhouette analysis</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" data-line-number="1"><span class="co"># identify and remove noise points</span></a>
<a class="sourceLine" id="cb114-2" data-line-number="2">noise &lt;-<span class="st"> </span>res<span class="op">$</span>cluster<span class="op">==</span><span class="dv">0</span></a></code></pre></div>
<p>Remove noise points from cluster results</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" data-line-number="1">clusters &lt;-<span class="st"> </span>res<span class="op">$</span>cluster[<span class="op">!</span>noise]</a></code></pre></div>
<p>Generate distance matrix from <code>noisy_moons</code> data.frame, exluding noise points.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" data-line-number="1">d &lt;-<span class="st"> </span><span class="kw">dist</span>(noisy_moons[<span class="op">!</span>noise,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])</a></code></pre></div>
<p>Silhouette analysis</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" data-line-number="1">clusterColours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">9</span>,<span class="st">&quot;Set1&quot;</span>)</a>
<a class="sourceLine" id="cb117-2" data-line-number="2">sil &lt;-<span class="st"> </span><span class="kw">silhouette</span>(clusters, d)</a>
<a class="sourceLine" id="cb117-3" data-line-number="3"><span class="kw">plot</span>(sil, <span class="dt">border=</span><span class="ot">NA</span>, <span class="dt">col=</span>clusterColours[<span class="kw">sort</span>(clusters)], <span class="dt">main=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/silhouetteNoisyMoonsDBSCAN-1.png" alt="Silhouette plot for DBSCAN clustering of the noisy moons data set." width="60%" />
<p class="caption">
Silhouette plot for DBSCAN clustering of the noisy moons data set.
</p>
</div>
<p>The silhouette analysis suggests that DBSCAN has found clusters of poor quality in the noisy moons data set. However, we saw by eye that it it did a good job of deliminiting the two clusters. The result demonstrates that the silhouette method is less useful when dealing with clusters that are defined by density, rather than inertia.</p>
</div>
</div>
<div id="example-gene-expression-profiling-of-human-tissues" class="section level2">
<h2><span class="header-section-number">4.8</span> Example: gene expression profiling of human tissues</h2>
<div id="hierarchic-agglomerative-2" class="section level3">
<h3><span class="header-section-number">4.8.1</span> Hierarchic agglomerative</h3>
<div id="basics" class="section level4">
<h4><span class="header-section-number">4.8.1.1</span> Basics</h4>
<p>Load required libraries</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" data-line-number="1"><span class="kw">library</span>(RColorBrewer)</a>
<a class="sourceLine" id="cb118-2" data-line-number="2"><span class="kw">library</span>(dendextend)</a></code></pre></div>
<p>Load data</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" data-line-number="1"><span class="kw">load</span>(<span class="st">&quot;data/tissues_gene_expression/tissuesGeneExpression.rda&quot;</span>)</a></code></pre></div>
<p>Inspect data</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" data-line-number="1"><span class="kw">table</span>(tissue)</a></code></pre></div>
<pre><code>## tissue
##  cerebellum       colon endometrium hippocampus      kidney       liver 
##          38          34          15          31          39          26 
##    placenta 
##           6</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" data-line-number="1"><span class="kw">dim</span>(e)</a></code></pre></div>
<pre><code>## [1] 22215   189</code></pre>
<p>Compute distance between each sample</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" data-line-number="1">d &lt;-<span class="st"> </span><span class="kw">dist</span>(<span class="kw">t</span>(e))</a></code></pre></div>
<p>perform hierarchical clustering</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" data-line-number="1">hc &lt;-<span class="st"> </span><span class="kw">hclust</span>(d, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>)</a>
<a class="sourceLine" id="cb125-2" data-line-number="2"><span class="kw">plot</span>(hc, <span class="dt">labels=</span>tissue, <span class="dt">cex=</span><span class="fl">0.5</span>, <span class="dt">hang=</span><span class="op">-</span><span class="dv">1</span>, <span class="dt">xlab=</span><span class="st">&quot;&quot;</span>, <span class="dt">sub=</span><span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueDendrogram-1.png" alt="Clustering of tissue samples based on gene expression profiles. " width="100%" />
<p class="caption">
Clustering of tissue samples based on gene expression profiles.
</p>
</div>
</div>
<div id="colour-labels" class="section level4">
<h4><span class="header-section-number">4.8.1.2</span> Colour labels</h4>
<p>The dendextend library can be used to plot dendrogram with colour labels</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" data-line-number="1">tissue_type &lt;-<span class="st"> </span><span class="kw">unique</span>(tissue)</a>
<a class="sourceLine" id="cb126-2" data-line-number="2">dend &lt;-<span class="st"> </span><span class="kw">as.dendrogram</span>(hc)</a>
<a class="sourceLine" id="cb126-3" data-line-number="3">dend_colours &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="kw">length</span>(<span class="kw">unique</span>(tissue)),<span class="st">&quot;Dark2&quot;</span>)</a>
<a class="sourceLine" id="cb126-4" data-line-number="4"><span class="kw">names</span>(dend_colours) &lt;-<span class="st"> </span>tissue_type</a>
<a class="sourceLine" id="cb126-5" data-line-number="5"><span class="kw">labels</span>(dend) &lt;-<span class="st"> </span>tissue[<span class="kw">order.dendrogram</span>(dend)]</a>
<a class="sourceLine" id="cb126-6" data-line-number="6"><span class="kw">labels_colors</span>(dend) &lt;-<span class="st"> </span>dend_colours[tissue][<span class="kw">order.dendrogram</span>(dend)]</a>
<a class="sourceLine" id="cb126-7" data-line-number="7"><span class="kw">labels_cex</span>(dend) =<span class="st"> </span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb126-8" data-line-number="8"><span class="kw">plot</span>(dend, <span class="dt">horiz=</span>T)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueDendrogramColour-1.png" alt="Clustering of tissue samples based on gene expression profiles with labels coloured by tissue type. " width="100%" />
<p class="caption">
Clustering of tissue samples based on gene expression profiles with labels coloured by tissue type.
</p>
</div>
</div>
<div id="defining-clusters-by-cutting-tree" class="section level4">
<h4><span class="header-section-number">4.8.1.3</span> Defining clusters by cutting tree</h4>
<p>Define clusters by cutting tree at a specific height</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" data-line-number="1"><span class="kw">plot</span>(dend, <span class="dt">horiz=</span>T)</a>
<a class="sourceLine" id="cb127-2" data-line-number="2"><span class="kw">abline</span>(<span class="dt">v=</span><span class="dv">125</span>, <span class="dt">lwd=</span><span class="dv">2</span>, <span class="dt">lty=</span><span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueDendrogramCutHeight-1.png" alt="Clusters found by cutting tree at a height of 125" width="100%" />
<p class="caption">
Clusters found by cutting tree at a height of 125
</p>
</div>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" data-line-number="1">hclusters &lt;-<span class="st"> </span><span class="kw">cutree</span>(dend, <span class="dt">h=</span><span class="dv">125</span>)</a>
<a class="sourceLine" id="cb128-2" data-line-number="2"><span class="kw">table</span>(tissue, <span class="dt">cluster=</span>hclusters)</a></code></pre></div>
<pre><code>##              cluster
## tissue         1  2  3  4  5  6
##   cerebellum   0 36  0  0  2  0
##   colon        0  0 34  0  0  0
##   endometrium 15  0  0  0  0  0
##   hippocampus  0 31  0  0  0  0
##   kidney      37  0  0  0  2  0
##   liver        0  0  0 24  2  0
##   placenta     0  0  0  0  0  6</code></pre>
<p>Select a specific number of clusters.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" data-line-number="1"><span class="kw">plot</span>(dend, <span class="dt">horiz=</span>T)</a>
<a class="sourceLine" id="cb130-2" data-line-number="2"><span class="kw">abline</span>(<span class="dt">v =</span> <span class="kw">heights_per_k.dendrogram</span>(dend)[<span class="st">&quot;8&quot;</span>], <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueDendrogramEightClusters-1.png" alt="Selection of eight clusters from the dendogram" width="100%" />
<p class="caption">
Selection of eight clusters from the dendogram
</p>
</div>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" data-line-number="1">hclusters &lt;-<span class="st"> </span><span class="kw">cutree</span>(dend, <span class="dt">k=</span><span class="dv">8</span>)</a>
<a class="sourceLine" id="cb131-2" data-line-number="2"><span class="kw">table</span>(tissue, <span class="dt">cluster=</span>hclusters)</a></code></pre></div>
<pre><code>##              cluster
## tissue         1  2  3  4  5  6  7  8
##   cerebellum   0 31  0  0  2  0  5  0
##   colon        0  0 34  0  0  0  0  0
##   endometrium  0  0  0  0  0 15  0  0
##   hippocampus  0 31  0  0  0  0  0  0
##   kidney      37  0  0  0  2  0  0  0
##   liver        0  0  0 24  2  0  0  0
##   placenta     0  0  0  0  0  0  0  6</code></pre>
</div>
<div id="heatmap" class="section level4">
<h4><span class="header-section-number">4.8.1.4</span> Heatmap</h4>
<p>Base R provides a <strong>heatmap</strong> function, but we will use the more advanced <strong>heatmap.2</strong> from the <strong>gplots</strong> package.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" data-line-number="1"><span class="kw">library</span>(gplots)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;gplots&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     lowess</code></pre>
<p>Define a colour palette (also known as a lookup table).</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" data-line-number="1">heatmap_colours &lt;-<span class="st"> </span><span class="kw">colorRampPalette</span>(<span class="kw">brewer.pal</span>(<span class="dv">9</span>, <span class="st">&quot;PuBuGn&quot;</span>))(<span class="dv">100</span>)</a></code></pre></div>
<p>Calculate the variance of each gene.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" data-line-number="1">geneVariance &lt;-<span class="st"> </span><span class="kw">apply</span>(e,<span class="dv">1</span>,var)</a></code></pre></div>
<p>Find the row numbers of the 40 genes with the highest variance.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" data-line-number="1">idxTop40 &lt;-<span class="st"> </span><span class="kw">order</span>(<span class="op">-</span>geneVariance)[<span class="dv">1</span><span class="op">:</span><span class="dv">40</span>]</a></code></pre></div>
<p>Define colours for tissues.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" data-line-number="1">tissueColours &lt;-<span class="st"> </span><span class="kw">palette</span>(<span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;Dark2&quot;</span>))[<span class="kw">as.numeric</span>(<span class="kw">as.factor</span>(tissue))]</a></code></pre></div>
<p>Plot heatmap.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" data-line-number="1"><span class="kw">heatmap.2</span>(e[idxTop40,], <span class="dt">labCol=</span>tissue, <span class="dt">trace=</span><span class="st">&quot;none&quot;</span>,</a>
<a class="sourceLine" id="cb140-2" data-line-number="2">          <span class="dt">ColSideColors=</span>tissueColours, <span class="dt">col=</span>heatmap_colours)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/heatmapTissueExpression-1.png" alt="Heatmap of the expression of the 40 genes with the highest variance." width="100%" />
<p class="caption">
Heatmap of the expression of the 40 genes with the highest variance.
</p>
</div>
</div>
</div>
<div id="k-means-2" class="section level3">
<h3><span class="header-section-number">4.8.2</span> K-means</h3>
<p>Load data if not already in workspace.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" data-line-number="1"><span class="kw">load</span>(<span class="st">&quot;data/tissues_gene_expression/tissuesGeneExpression.rda&quot;</span>)</a></code></pre></div>
<p>As we saw earlier, the data set contains expression levels for over 22,000 transcripts in seven tissues.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" data-line-number="1"><span class="kw">table</span>(tissue)</a></code></pre></div>
<pre><code>## tissue
##  cerebellum       colon endometrium hippocampus      kidney       liver 
##          38          34          15          31          39          26 
##    placenta 
##           6</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1"><span class="kw">dim</span>(e)</a></code></pre></div>
<pre><code>## [1] 22215   189</code></pre>
<p>First we will examine the total intra-cluster variance with different values of <em>k</em>. Our data-set is fairly large, so clustering it for several values or <em>k</em> and with multiple random starting centres is computationally quite intensive. Fortunately the task readily lends itself to parallelization; we can assign the analysis of each ‘k’ to a different processing core. As we have seen in the previous chapters on supervised learning, <a href="http://cran.r-project.org/web/packages/caret/index.html">caret</a> has parallel processing built in and we simply have to load a package for multicore processing, such as <a href="http://cran.r-project.org/web/packages/doMC/index.html">doMC</a>, and then register the number of cores we would like to use. Running <strong>kmeans</strong> in parallel is slightly more involved, but still very easy. We will start by loading <a href="http://cran.r-project.org/web/packages/doMC/index.html">doMC</a> and registering all available cores:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" data-line-number="1"><span class="kw">library</span>(doMC)</a></code></pre></div>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## Loading required package: iterators</code></pre>
<pre><code>## Loading required package: parallel</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1"><span class="kw">registerDoMC</span>(<span class="kw">detectCores</span>())</a></code></pre></div>
<p>To find out how many cores we have registered we can use:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" data-line-number="1"><span class="kw">getDoParWorkers</span>()</a></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p>Instead of using the <strong>lapply</strong> function to vectorize our code, we will instead use the parallel equivalent, <strong>foreach</strong>. Like <strong>lapply</strong>, <strong>foreach</strong> returns a list by default. For this example we have set a seed, rather than generate a random number, for the sake of reproducibility. Ordinarily we would omit <code>set.seed(42)</code> and <code>.options.multicore=list(set.seed=FALSE)</code>.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" data-line-number="1">k&lt;-<span class="dv">1</span><span class="op">:</span><span class="dv">15</span></a>
<a class="sourceLine" id="cb153-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">42</span>)</a>
<a class="sourceLine" id="cb153-3" data-line-number="3">res_k_<span class="dv">15</span> &lt;-<span class="st"> </span><span class="kw">foreach</span>(</a>
<a class="sourceLine" id="cb153-4" data-line-number="4">  <span class="dt">i=</span>k, </a>
<a class="sourceLine" id="cb153-5" data-line-number="5">  <span class="dt">.options.multicore=</span><span class="kw">list</span>(<span class="dt">set.seed=</span><span class="ot">FALSE</span>)) <span class="op">%dopar%</span><span class="st"> </span><span class="kw">kmeans</span>(<span class="kw">t</span>(e), i, <span class="dt">nstart=</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb153-6" data-line-number="6"><span class="kw">plot_tot_withinss</span>(res_k_<span class="dv">15</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueExpressionElbow-1.png" alt="K-means clustering of human tissue gene expression: variance within clusters." width="100%" />
<p class="caption">
K-means clustering of human tissue gene expression: variance within clusters.
</p>
</div>
<!--
set.seed(42)
res_k_15 <- lapply(k, function(i){kmeans(t(e), i, nstart=10)})
-->
<p>There is no obvious elbow, but since we know that there are seven tissues in the data set we will try k=7.
<!--

```r
set.seed(42)
res <- kmeans(t(e), 7, nstart=10)
table(tissue, res$cluster)
```

```
##              
## tissue         1  2  3  4  5  6  7
##   cerebellum  33  5  0  0  0  0  0
##   colon        0  0  0  0  0 34  0
##   endometrium  0  0 15  0  0  0  0
##   hippocampus  0 31  0  0  0  0  0
##   kidney       0  0  0 39  0  0  0
##   liver        0  0  0  0 26  0  0
##   placenta     0  0  0  0  0  0  6
```
--></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" data-line-number="1"><span class="kw">table</span>(tissue, res_k_<span class="dv">15</span>[[<span class="dv">7</span>]]<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>##              
## tissue         1  2  3  4  5  6  7
##   cerebellum  33  5  0  0  0  0  0
##   colon        0  0  0  0  0 34  0
##   endometrium  0  0 15  0  0  0  0
##   hippocampus  0 31  0  0  0  0  0
##   kidney       0  0  0 39  0  0  0
##   liver        0  0  0  0 26  0  0
##   placenta     0  0  0  0  0  0  6</code></pre>
<p>The analysis has found a distinct cluster for each tissue and therefore performed slightly better than the earlier hierarchical clustering analysis, which placed endometrium and kidney observations in the same cluster.</p>
<p>To visualize the result in a 2D scatter plot we first need to apply dimensionality reduction. We will use principal component analysis (PCA), which was described in chapter <a href="dimensionality-reduction.html#dimensionality-reduction">3</a>.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" data-line-number="1">pca &lt;-<span class="st"> </span><span class="kw">prcomp</span>(<span class="kw">t</span>(e))</a>
<a class="sourceLine" id="cb156-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="dt">data=</span><span class="kw">as.data.frame</span>(pca<span class="op">$</span>x), <span class="kw">aes</span>(PC1,PC2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span><span class="kw">brewer.pal</span>(<span class="dv">7</span>,<span class="st">&quot;Dark2&quot;</span>)[res_k_<span class="dv">15</span>[[<span class="dv">7</span>]]<span class="op">$</span>cluster], </a>
<a class="sourceLine" id="cb156-4" data-line-number="4">             <span class="dt">shape=</span><span class="kw">c</span>(<span class="dv">49</span><span class="op">:</span><span class="dv">55</span>)[res_k_<span class="dv">15</span>[[<span class="dv">7</span>]]<span class="op">$</span>cluster], <span class="dt">size=</span><span class="dv">5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb156-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueExpressionPCA-1.png" alt="K-means clustering of human gene expression (k=7): scatterplot of first two principal components." width="50%" />
<p class="caption">
K-means clustering of human gene expression (k=7): scatterplot of first two principal components.
</p>
</div>
</div>
<div id="dbscan-2" class="section level3">
<h3><span class="header-section-number">4.8.3</span> DBSCAN</h3>
<p>Load data if not already in workspace.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" data-line-number="1"><span class="kw">load</span>(<span class="st">&quot;data/tissues_gene_expression/tissuesGeneExpression.rda&quot;</span>)</a></code></pre></div>
<p>Get a summary of the data set.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" data-line-number="1"><span class="kw">table</span>(tissue)</a></code></pre></div>
<pre><code>## tissue
##  cerebellum       colon endometrium hippocampus      kidney       liver 
##          38          34          15          31          39          26 
##    placenta 
##           6</code></pre>
<p>We’ll try k=5 (default for dbscan), because there are only six observations for placenta.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" data-line-number="1"><span class="kw">kNNdistplot</span>(<span class="kw">t</span>(e), <span class="dt">k=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb160-2" data-line-number="2"><span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">85</span>)</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueExpressionKNNdist-1.png" alt="Five-nearest neighbour distances for the gene expression profiling of human tissues data set." width="75%" />
<p class="caption">
Five-nearest neighbour distances for the gene expression profiling of human tissues data set.
</p>
</div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">42</span>)</a>
<a class="sourceLine" id="cb161-2" data-line-number="2">res &lt;-<span class="st"> </span>dbscan<span class="op">::</span><span class="kw">dbscan</span>(<span class="kw">t</span>(e), <span class="dt">eps=</span><span class="dv">85</span>, <span class="dt">minPts=</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb161-3" data-line-number="3"><span class="kw">table</span>(res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>## 
##  0  1  2  3  4  5  6 
## 12 37 62 34 24 15  5</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" data-line-number="1"><span class="kw">table</span>(tissue, res<span class="op">$</span>cluster)</a></code></pre></div>
<pre><code>##              
## tissue         0  1  2  3  4  5  6
##   cerebellum   2  0 31  0  0  0  5
##   colon        0  0  0 34  0  0  0
##   endometrium  0  0  0  0  0 15  0
##   hippocampus  0  0 31  0  0  0  0
##   kidney       2 37  0  0  0  0  0
##   liver        2  0  0  0 24  0  0
##   placenta     6  0  0  0  0  0  0</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" data-line-number="1">pca &lt;-<span class="st"> </span><span class="kw">prcomp</span>(<span class="kw">t</span>(e))</a>
<a class="sourceLine" id="cb165-2" data-line-number="2"><span class="kw">ggplot</span>(<span class="dt">data=</span><span class="kw">as.data.frame</span>(pca<span class="op">$</span>x), <span class="kw">aes</span>(PC1,PC2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb165-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span><span class="kw">brewer.pal</span>(<span class="dv">8</span>,<span class="st">&quot;Dark2&quot;</span>)[<span class="kw">c</span>(<span class="dv">8</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>)][res<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>], </a>
<a class="sourceLine" id="cb165-4" data-line-number="4">             <span class="dt">shape=</span><span class="kw">c</span>(<span class="dv">48</span><span class="op">:</span><span class="dv">55</span>)[res<span class="op">$</span>cluster<span class="op">+</span><span class="dv">1</span>], <span class="dt">size=</span><span class="dv">5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb165-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/tissueExpressionDBSCANscatter-1.png" alt="Clustering of human tissue gene expression: scatterplot of first two principal components." width="60%" />
<p class="caption">
Clustering of human tissue gene expression: scatterplot of first two principal components.
</p>
</div>
</div>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">4.9</span> Exercises</h2>
<div id="clusteringEx1" class="section level3">
<h3><span class="header-section-number">4.9.1</span> Exercise 1</h3>
<p>Image segmentation is used to partition digital images into distinct regions containing pixels with similar attributes. Applications include identifying objects or structures in biomedical images. The aim of this exercise is to use k-means clustering to segment the image of a histological section of lung tissue (figure <a href="#fig:lungHistology"><strong>??</strong></a>) into distinct biological structures, based on pixel colour.</p>
<div class="figure" style="text-align: center">
<img src="data/histology/Emphysema_H_and_E.jpg" alt="Image of haematoxylin and eosin (H&amp;E) stained section of lung tissue from a patient with end-stage emphysema. CC BY 2.0, https://commons.wikimedia.org/w/index.php?curid=437645." width="80%" />
<p class="caption">
Image of haematoxylin and eosin (H&amp;E) stained section of lung tissue from a patient with end-stage emphysema. CC BY 2.0, <a href="https://commons.wikimedia.org/w/index.php?curid=437645" class="uri">https://commons.wikimedia.org/w/index.php?curid=437645</a>.
</p>
</div>
<p>The haematoxylin and eosin (H &amp; E) staining reveals four types of biological objects, identified by the following colours:</p>
<ul>
<li>blue-purple: cell nuclei</li>
<li>red: red blood cells</li>
<li>pink: other cell bodies and extracellular material</li>
<li>white: air spaces</li>
</ul>
<p><strong>Consider the following questions:</strong></p>
<ul>
<li>Can k-means clustering find the four biological objects in the image based on pixel colour?</li>
<li>Earlier we saw that if we plot the total within-cluster sum of squares against k, the position of the “elbow” is a useful guide to choosing the appropriate value of k (see section <a href="clustering.html#choosingK">4.4.3</a>. According to the “elbow” method, how many distinct clusters (colours) of pixels are present in the image?</li>
</ul>
<p><strong>Hints:</strong>
If you haven’t worked with images in R before, you may find the following information helpful.</p>
<p>The package <a href="https://bioconductor.org/packages/EBImage/">EBImage</a> provides a suite of tools for working with images. We will use it to read the file containing the image of the lung section.</p>
<!--EBImage needs methods library, but doesn't import it -->
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1"><span class="kw">library</span>(EBImage)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;EBImage&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dendextend&#39;:
## 
##     rotate</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" data-line-number="1"><span class="kw">library</span>(methods)</a>
<a class="sourceLine" id="cb169-2" data-line-number="2">img &lt;-<span class="st"> </span><span class="kw">readImage</span>(<span class="st">&quot;data/histology/Emphysema_H_and_E.jpg&quot;</span>)</a></code></pre></div>
<p><code>img</code> is an object of the <a href="https://bioconductor.org/packages/EBImage/">EBImage</a> class Image; it is essentially a multidimensional array containing the pixel intensities. To see the dimensions of the array, run:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1"><span class="kw">dim</span>(img)</a></code></pre></div>
<pre><code>## [1] 528 393   3</code></pre>
<p>In the case of this colour image, the array is 3-dimensional with 528 x 393 x 3 elements. These dimensions correspond to the image width (in pixels), image height and number of colour channels, respectively. The colour channels are red, green and blue (RGB).</p>
<p>Before we can cluster the pixels on colour, we need to convert the 3D array into a 2D data.frame (or matrix). Specifically, we require a data.frame (or matrix) where rows represent pixels and there is a column for the intensity of each of the three colour channels. We also need columns for the x and y coordinates of each pixel.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1">imgDim &lt;-<span class="st"> </span><span class="kw">dim</span>(img)</a>
<a class="sourceLine" id="cb172-2" data-line-number="2">imgDF &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb172-3" data-line-number="3">  <span class="dt">x =</span> <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span>imgDim[<span class="dv">1</span>], imgDim[<span class="dv">2</span>]),</a>
<a class="sourceLine" id="cb172-4" data-line-number="4">  <span class="dt">y =</span> <span class="kw">rep</span>(imgDim[<span class="dv">2</span>]<span class="op">:</span><span class="dv">1</span>, <span class="dt">each=</span>imgDim[<span class="dv">1</span>]),</a>
<a class="sourceLine" id="cb172-5" data-line-number="5">  <span class="dt">r =</span> <span class="kw">as.vector</span>(img[,,<span class="dv">1</span>]),</a>
<a class="sourceLine" id="cb172-6" data-line-number="6">  <span class="dt">g =</span> <span class="kw">as.vector</span>(img[,,<span class="dv">2</span>]),</a>
<a class="sourceLine" id="cb172-7" data-line-number="7">  <span class="dt">b =</span> <span class="kw">as.vector</span>(img[,,<span class="dv">3</span>])</a>
<a class="sourceLine" id="cb172-8" data-line-number="8">)</a></code></pre></div>
<p>If the data in <code>imgDF</code> are correct, we should be able to display the image using ggplot:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> imgDF, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb173-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">colour =</span> <span class="kw">rgb</span>(imgDF[<span class="kw">c</span>(<span class="st">&quot;r&quot;</span>, <span class="st">&quot;g&quot;</span>, <span class="st">&quot;b&quot;</span>)])) <span class="op">+</span></a>
<a class="sourceLine" id="cb173-3" data-line-number="3"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;x&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb173-4" data-line-number="4"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;y&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb173-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_minimal</span>()</a></code></pre></div>
<div class="figure" style="text-align: center">
<img src="03-clustering_files/figure-html/recreatedLungHistology-1.png" alt="Image of lung tissue recreated from reshaped data." width="80%" />
<p class="caption">
Image of lung tissue recreated from reshaped data.
</p>
</div>
<p>This should be all the information you need to perform this exercise.</p>
<p><strong>Solutions to exercises can be found in appendix <a href="solutions-clustering.html#solutions-clustering">C</a>.</strong></p>

</div>
</div>
</div>
<h3><span class="header-section-number">K</span> Solutions for use case 2</h3>
<div id="refs" class="references">
<div id="ref-Gionis2007">
<p>Gionis, A., H. Mannila, and P. Tsaparas. 2007. “Clustering aggregation.” <em>ACM Transactions on Knowledge Discovery from Data (TKDD)</em> 1 (1): 1–30.</p>
</div>
<div id="ref-Schubert2017">
<p>Schubert, Erich, Jörg Sander, Martin Ester, Hans Peter Kriegel, and Xiaowei Xu. 2017. “DBSCAN Revisited, Revisited: Why and How You Should (Still) Use Dbscan.” <em>ACM Trans. Database Syst.</em> 42 (3): 19:1–19:21. <a href="https://doi.org/10.1145/3068335">https://doi.org/10.1145/3068335</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dimensionality-reduction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="nearest-neighbours.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
